vjs.Youtube=function(a,b,c){vjs.MediaTechController.call(this,a,b,c);if((a=b.source.src.match(/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/))&&11==a[2].length)if(this.videoId=a[2],!this.player_.options_.ytcontrols){this.player_.poster("http://img.youtube.com/vi/"+this.videoId+"/0.jpg");var d=this;setTimeout(function(){d.player_.posterImage.el_.style.backgroundSize="cover"},50)}this.id_=this.player_.id()+"_youtube_api";a={enablejsapi:1,iv_load_policy:3,playerapiid:this.id(),disablekb:1,
controls:this.player_.options_.ytcontrols?1:0,showinfo:0,modestbranding:1,rel:0,origin:window.location.origin,autoplay:this.player_.options_.autoplay?1:0,loop:this.player_.options_.loop?1:0};this.el_.src="http://www.youtube.com/embed/"+this.videoId+"?"+vjs.Youtube.makeQueryString(a);this.player_.options_.ytcontrols&&(d=this,setTimeout(function(){d.player_.bigPlayButton.hide()},50));vjs.Youtube.apiReady?this.loadYoutube():(vjs.Youtube.loadingQueue.push(this),vjs.Youtube.apiLoading||(a=vjs.createEl("script",
{src:"http://www.youtube.com/iframe_api"}),b=document.getElementsByTagName("script")[0],b.parentNode.insertBefore(a,b),vjs.Youtube.apiLoading=!0))};goog.inherits(vjs.Youtube,vjs.MediaTechController);vjs.Youtube.prototype.dispose=function(){vjs.Youtube.superClass_.dispose.call(this);this.ytplayer.destroy()};
vjs.Youtube.prototype.createEl=function(){var a=this.player_,b=vjs.createEl("iframe",{id:a.id()+"_youtube_api",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0,webkitAllowFullScreen:"",mozallowfullscreen:"",allowFullScreen:""});vjs.insertFirst(b,a.el());return b};vjs.Youtube.prototype.play=function(){this.player_.isReady_?this.ytplayer.playVideo():(this.playOnReady=!0,this.player_.options.ytcontrols||this.player_.bigPlayButton.show())};vjs.Youtube.prototype.pause=function(){this.ytplayer.pauseVideo()};
vjs.Youtube.prototype.paused=function(){return this.lastState!==YT.PlayerState.PLAYING&&this.lastState!==YT.PlayerState.BUFFERING};vjs.Youtube.prototype.currentTime=function(){return this.ytplayer.getCurrentTime()};vjs.Youtube.prototype.setCurrentTime=function(a){this.ytplayer.seekTo(a,!0);this.player_.trigger("timeupdate")};vjs.Youtube.prototype.duration=function(){return this.ytplayer.getDuration()};
vjs.Youtube.prototype.buffered=function(){var a=this.ytplayer.getVideoBytesLoaded(),b=this.ytplayer.getVideoBytesTotal();if(!a||!b)return 0;var c=this.ytplayer.getDuration(),a=a/b*c,b=this.ytplayer.getVideoStartBytes()/b*c;return vjs.createTimeRange(b,b+a)};vjs.Youtube.prototype.volume=function(){isNaN(this.volumeVal)&&(this.volumeVal=this.ytplayer.getVolume()/100);return this.volumeVal};
vjs.Youtube.prototype.setVolume=function(a){a&&a!=this.volumeVal&&(this.ytplayer.setVolume(100*a),this.volumeVal=a,this.player_.trigger("volumechange"))};vjs.Youtube.prototype.muted=function(){return this.ytplayer.isMuted()};vjs.Youtube.prototype.setMuted=function(a){a?this.ytplayer.mute():this.ytplayer.unMute();var b=this;setTimeout(function(){b.player_.trigger("volumechange")},50)};
vjs.Youtube.prototype.onReady=function(){this.player_.trigger("techready");this.player_.posterImage.hide();this.triggerReady();this.player_.trigger("durationchange");this.playOnReady&&(this.player_.bigPlayButton.hide(),this.ytplayer.playVideo());(!this.player_.options_.controls||this.player_.options_.ytcontrols)&&this.player_.controlBar.hide()};
vjs.Youtube.prototype.onStateChange=function(a){if(a!=this.lastState){switch(a){case -1:this.player_.trigger("durationchange");break;case YT.PlayerState.ENDED:this.player_.trigger("ended");this.player_.options_.ytcontrols||this.player_.bigPlayButton.show();break;case YT.PlayerState.PLAYING:this.player_.trigger("timeupdate");this.player_.trigger("durationchange");this.player_.trigger("playing");this.player_.trigger("play");break;case YT.PlayerState.PAUSED:this.player_.trigger("pause");break;case YT.PlayerState.BUFFERING:this.player_.trigger("timeupdate"),
this.player_.trigger("waiting"),this.player_.loadingSpinner.hide()}this.lastState=a}};
vjs.Youtube.prototype.onPlaybackQualityChange=function(a){switch(a){case "medium":this.player_.videoWidth=480;this.player_.videoHeight=360;break;case "large":this.player_.videoWidth=640;this.player_.videoHeight=480;break;case "hd720":this.player_.videoWidth=960;this.player_.videoHeight=720;break;case "hd1080":this.player_.videoWidth=1440;this.player_.videoHeight=1080;break;case "highres":this.player_.videoWidth=1920;this.player_.videoHeight=1080;break;case "small":this.player_.videoWidth=320;this.player_.videoHeight=
240;break;default:this.player_.videoWidth=0,this.player_.videoHeight=0}this.player_.trigger("ratechange")};vjs.Youtube.prototype.onError=function(a){this.player_.error=a;this.player_.trigger("error")};vjs.Youtube.isSupported=function(){return!0};vjs.Youtube.canPlaySource=function(a){return"video/youtube"==a.type};vjs.Youtube.prototype.features={fullscreen:!0,volumeControl:!0,progressEvents:!1,timeupdateEvents:!1};vjs.Youtube.loadingQueue=[];
vjs.Youtube.prototype.loadYoutube=function(){this.ytplayer=new YT.Player(this.id(),{events:{onReady:function(a){a.target.vjsTech.onReady()},onStateChange:function(a){a.target.vjsTech.onStateChange(a.data)},onPlaybackQualityChange:function(a){a.target.vjsTech.onPlaybackQualityChange(a.data)},onError:function(a){a.target.vjsTech.onError(a.data)}}});this.ytplayer.vjsTech=this};
vjs.Youtube.makeQueryString=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")};window.onYouTubeIframeAPIReady=function(){for(var a;a=vjs.Youtube.loadingQueue.shift();)a.loadYoutube();vjs.Youtube.loadingQueue=[]};