var c=void 0,f=!0,h=null,j=!1;function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,aa=this;aa.hc=f;Math.floor(2147483648*Math.random()).toString(36);function r(a,b){var d=a.split("."),e=aa;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==c?e[g]=b:e=e[g]?e[g]:e[g]={}}function t(a,b){function d(){}d.prototype=b.prototype;a.e=b.prototype;a.prototype=new d;a.prototype.constructor=a}document.createElement("video");
document.createElement("audio");function u(a,b,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.oa[a])return u.oa[a];a=u.l(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new v(a,b,d)}var ba=u;u.Ya="GENERATED_CDN_VSN";u.Xa="https:"==document.location.protocol?"https://":"http://";
u.options={techOrder:["html5","flash"],html5:{},flash:{sc:u.Xa+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.oa={};"GENERATED_CDN_VSN"!=u.Ya&&(ba.options.flash.swf=u.Xa+"vjs.zencdn.net/"+u.Ya+"/video-js.swf");
u.c=function(a,b,d){var e=u.getData(a);e.q||(e.q={});e.q[b]||(e.q[b]=[]);d.p||(d.p=u.p++);e.q[b].push(d);e.J||(e.disabled=j,e.J=function(b){if(!e.disabled){b=u.gb(b);var d=e.q[b.type];if(d)for(var d=d.slice(0),k=0,s=d.length;k<s&&!b.kb();k++)d[k].call(a,b)}});1==e.q[b].length&&(document.addEventListener?a.addEventListener(b,e.J,j):document.attachEvent&&a.attachEvent("on"+b,e.J))};
u.o=function(a,b,d){if(u.jb(a)){var e=u.getData(a);if(e.q)if(b){var g=e.q[b];if(g){if(d){if(d.p)for(e=0;e<g.length;e++)g[e].p===d.p&&g.splice(e--,1)}else e.q[b]=[];u.ab(a,b)}}else for(g in e.q)b=g,e.q[b]=[],u.ab(a,b)}};u.ab=function(a,b){var d=u.getData(a);0===d.q[b].length&&(delete d.q[b],document.removeEventListener?a.removeEventListener(b,d.J,j):document.detachEvent&&a.detachEvent("on"+b,d.J));u.Ia(d.q)&&(delete d.q,delete d.J,delete d.disabled);u.Ia(d)&&u.ob(a)};
u.gb=function(a){function b(){return f}function d(){return j}if(!a||!a.Ja){var e=a||window.event,g;for(g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=j;a.ia=b};a.ia=d;a.stopPropagation=function(){a.cancelBubble=f;a.Ja=b};a.Ja=d;a.stopImmediatePropagation=function(){a.kb=b;a.stopPropagation()};a.kb=d;a.clientX!=h&&(e=document.documentElement,g=document.body,a.pageX=a.clientX+(e&&
e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0));a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.i=function(a,b){var d=u.jb(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof b&&(b={type:b,target:a});b=u.gb(b);d.J&&d.J.call(a,b);if(e&&!b.Ja())u.i(e,b);else if(!e&&!b.ia()&&(d=u.getData(b.target),b.target[b.type])){d.disabled=f;if("function"===typeof b.target[b.type])b.target[b.type]();d.disabled=j}return!b.ia()};u.F=function(a,b,d){u.c(a,b,function(){u.o(a,b,arguments.callee);d.apply(this,arguments)})};
u.d=function(a,b){var d=document.createElement(a||"div"),e;for(e in b)b.hasOwnProperty(e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,b[e]):d[e]=b[e]);return d};u.M=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.h={};u.h.toString=Object.prototype.toString;u.h.hasOwnProperty=Object.prototype.hasOwnProperty;u.h.Y=function(a,b,d){for(var e in a)u.h.hasOwnProperty.call(a,e)&&b.call(d||this,e,a[e])};
u.h.v=function(a,b){if(!b)return a;for(var d in b)u.h.hasOwnProperty.call(b,d)&&(a[d]=b[d]);return a};u.h.fb=function(a,b){var d,e,g;a=u.h.copy(a);for(d in b)u.h.hasOwnProperty.call(b,d)&&(e=a[d],g=b[d],a[d]="[object Object]"===u.h.toString.call(e)&&"[object Object]"===u.h.toString.call(g)?u.h.fb(e,g):b[d]);return a};u.h.copy=function(a){return u.h.v({},a)};u.bind=function(a,b,d){function e(){return b.apply(a,arguments)}b.p||(b.p=u.p++);e.p=d?d+"_"+b.p:b.p;return e};u.X={};u.p=1;
u.expando="vdata"+(new Date).getTime();u.getData=function(a){var b=a[u.expando];b||(b=a[u.expando]=u.p++,u.X[b]={});return u.X[b]};u.jb=function(a){a=a[u.expando];return!(!a||u.Ia(u.X[a]))};u.ob=function(a){var b=a[u.expando];if(b){delete u.X[b];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.Ia=function(a){for(var b in a)if(a[b]!==h)return j;return f};
u.m=function(a,b){-1==(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className=""===a.className?b:a.className+" "+b)};u.s=function(a,b){if(-1!=a.className.indexOf(b)){var d=a.className.split(" ");d.splice(d.indexOf(b),1);a.className=d.join(" ")}};u.wa=u.d("video");u.H=navigator.userAgent;u.yb=!!u.H.match(/iPhone/i);u.xb=!!u.H.match(/iPad/i);u.zb=!!u.H.match(/iPod/i);u.wb=u.yb||u.xb||u.zb;var ca=u,da;var ea=u.H.match(/OS (\d+)_/i);da=ea&&ea[1]?ea[1]:c;ca.ic=da;u.ub=!!u.H.match(/Android.*AppleWebKit/i);
var fa=u,ga=u.H.match(/Android (\d+)\./i);fa.tb=ga&&ga[1]?ga[1]:h;u.vb=function(){return!!u.H.match("Firefox")};u.Fa=function(a){var b={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,p=d.length-1;0<=p;p--){e=d[p].name;g=d[p].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;b[e]=g}return b};
u.nc=function(a,b){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle[b]);return d};u.Ha=function(a,b){b.firstChild?b.insertBefore(a,b.firstChild):b.appendChild(a)};u.Va={};u.l=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.ha=function(a,b){b=b||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),p=Math.floor(b/60%60),k=Math.floor(b/3600),g=0<g||0<k?g+":":"";return g+(((g||10<=p)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Cb=function(){document.body.focus();document.onselectstart=m(j)};u.dc=function(){document.onselectstart=m(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,b){b||(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};
u.Ba=function(a,b){return{length:1,start:function(){return a},end:function(){return b}}};
u.get=function(a,b,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(p){d(p)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?b(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.Yb=function(a){var b=window.localStorage||j;if(b)try{b.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.ib=function(a){a.match(/^https?:\/\//)||(a=u.d("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Ib="getBoundingClientRect"in document.documentElement?function(a){var b;try{b=a.getBoundingClientRect()}catch(d){}if(!b)return 0;a=document.body;return b.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var b=a.offsetLeft;a=a.offsetParent;)b+=a.offsetLeft;return b};
function x(a,b,d){this.b=a;this.f=u.h.copy(this.f);b=this.options(b);this.C=b.id||(b.el&&b.el.id?b.el.id:a.id()+"_component_"+u.p++);this.Lb=b.name||h;this.a=b.el||this.d();this.w=[];this.za={};this.I={};if((a=this.f)&&a.children){var e=this;u.h.Y(a.children,function(a,b){b!==j&&!b.loadEvent&&(e[a]=e.K(a,b))})}y(this,d)}n=x.prototype;
n.z=function(){if(this.w)for(var a=this.w.length-1;0<=a;a--)this.w[a].z&&this.w[a].z();this.I=this.za=this.w=h;this.o();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.ob(this.a);this.a=h};n.Sb=l("b");n.options=function(a){return a===c?this.f:this.f=u.h.fb(this.f,a)};n.d=function(a,b){return u.d(a,b)};n.l=l("a");n.id=l("C");n.name=l("Lb");n.children=l("w");
n.K=function(a,b){var d,e;"string"===typeof a?(e=a,b=b||{},d=b.componentClass||u.M(e),b.name=e,d=new window.videojs[d](this.b||this,b)):d=a;this.w.push(d);"function"===typeof d.id&&(this.za[d.id()]=d);(e=e||d.name&&d.name())&&(this.I[e]=d);"function"===typeof d.el&&d.el()&&this.a.appendChild(d.el());return d};
n.removeChild=function(a){"string"===typeof a&&(a=this.I[a]);if(a&&this.w){for(var b=j,d=this.w.length-1;0<=d;d--)if(this.w[d]===a){b=f;this.w.splice(d,1);break}b&&(this.za[a.id]=h,this.I[a.name]=h,(b=a.l())&&b.parentNode===this.a&&this.a.removeChild(a.l()))}};n.t=m("");n.c=function(a,b){u.c(this.a,a,u.bind(this,b));return this};n.o=function(a,b){u.o(this.a,a,b);return this};n.F=function(a,b){u.F(this.a,a,u.bind(this,b));return this};n.i=function(a,b){u.i(this.a,a,b);return this};
function y(a,b){b&&(a.N?b.call(a):(a.ra===c&&(a.ra=[]),a.ra.push(b)))}n.ua=function(){this.N=f;var a=this.ra;if(a&&0<a.length){for(var b=0,d=a.length;b<d;b++)a[b].call(this);this.ra=[];this.i("ready")}};n.m=function(a){u.m(this.a,a);return this};n.s=function(a){u.s(this.a,a);return this};n.show=function(){this.a.style.display="block";return this};n.u=function(){this.a.style.display="none";return this};n.$=function(){this.s("vjs-fade-out");this.m("vjs-fade-in");return this};
n.ga=function(){this.s("vjs-fade-in");this.m("vjs-fade-out");return this};n.lb=function(){var a=this.a.style;a.display="block";a.opacity=1;a.fc="visible";return this};function ha(a){a=a.a.style;a.display="";a.opacity="";a.fc=""}n.width=function(a,b){return ia(this,"width",a,b)};n.height=function(a,b){return ia(this,"height",a,b)};n.Fb=function(a,b){return this.width(a,f).height(b)};
function ia(a,b,d,e){if(d!==c)return a.a.style[b]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.i("resize"),a;if(!a.a)return 0;d=a.a.style[b];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.M(b)],10)}
function v(a,b,d){this.G=a;b=u.h.v(ja(a),b);this.n={};this.nb=b.poster;this.bb=b.controls;x.call(this,this,b,d);this.F("play",function(a){u.i(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.c("ended",this.Nb);this.c("play",this.Ra);this.c("firstplay",this.Ob);this.c("pause",this.Qa);this.c("progress",this.Qb);this.c("durationchange",this.Mb);this.c("error",this.Na);this.c("fullscreenchange",this.Pb);u.oa[this.C]=this;b.plugins&&
u.h.Y(b.plugins,function(a,b){this[a](b)},this)}t(v,x);n=v.prototype;n.f=u.options;n.z=function(){u.oa[this.C]=h;this.G&&this.G.player&&(this.G.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.qa);this.ba();this.g&&this.g.z();v.e.z.call(this)};
function ja(a){var b={sources:[],tracks:[]};u.h.v(b,u.Fa(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,p=e.length;g<p;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?b.sources.push(u.Fa(a)):"track"===d&&b.tracks.push(u.Fa(a));return b}
n.d=function(){var a=this.a=v.e.d.call(this,"div"),b=this.G;b.removeAttribute("controls");b.removeAttribute("width");b.removeAttribute("height");if(b.hasChildNodes())for(var d=b.childNodes.length,e=0,g=b.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&b.removeChild(g[0]);b.id=b.id||"vjs_video_"+u.p++;a.id=b.id;a.className=b.className;b.id+="_html5_api";b.className="vjs-tech";b.player=a.player=this;this.m("vjs-paused");this.width(this.f.width,f);this.height(this.f.height,
f);b.parentNode&&b.parentNode.insertBefore(a,b);u.Ha(b,a);return a};
function ka(a,b,d){a.g?la(a):"Html5"!==b&&a.G&&(a.a.removeChild(a.G),a.G=h);a.P=b;a.N=j;var e=u.h.v({source:d,parentEl:a.a},a.f[b.toLowerCase()]);d&&(d.src==a.n.src&&0<a.n.currentTime&&(e.startTime=a.n.currentTime),a.n.src=d.src);a.g=new window.videojs[b](a,e);y(a.g,function(){this.b.ua();if(!this.j.Ta){var a=this.b;a.La=f;a.qa=setInterval(u.bind(a,function(){this.n.ya<this.buffered().end(0)?this.i("progress"):1==ma(this)&&(clearInterval(this.qa),this.i("progress"))}),500);a.g.F("progress",function(){this.j.Ta=
f;var a=this.b;a.La=j;clearInterval(a.qa)})}this.j.Wa||(a=this.b,a.Ma=f,a.c("play",a.sb),a.c("pause",a.ba),a.g.F("timeupdate",function(){this.j.Wa=f;na(this.b)}))})}function la(a){a.N=j;a.g.z();a.La&&(a.La=j,clearInterval(a.qa));a.Ma&&na(a);a.g=j}function na(a){a.Ma=j;a.ba();a.o("play",a.sb);a.o("pause",a.ba)}n.sb=function(){this.eb&&this.ba();this.eb=setInterval(u.bind(this,function(){this.i("timeupdate")}),250)};n.ba=function(){clearInterval(this.eb)};
n.Nb=function(){this.f.loop&&(this.currentTime(0),this.play())};n.Ra=function(){u.s(this.a,"vjs-paused");u.m(this.a,"vjs-playing")};n.Ob=function(){this.f.starttime&&this.currentTime(this.f.starttime)};n.Qa=function(){u.s(this.a,"vjs-playing");u.m(this.a,"vjs-paused")};n.Qb=function(){1==ma(this)&&this.i("loadedalldata")};n.Mb=function(){this.duration(z(this,"duration"))};n.Na=function(a){u.log("Video Error",a)};n.Pb=function(){this.D?this.m("vjs-fullscreen"):this.s("vjs-fullscreen")};
function A(a,b,d){if(a.g&&a.g.N)y(a.g,function(){this[b](d)});else try{a.g[b](d)}catch(e){u.log(e)}}function z(a,b){if(a.g.N)try{return a.g[b]()}catch(d){if(a.g[b]===c)u.log("Video.js: "+b+" method not defined for "+a.P+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+b+" unavailable on "+a.P+" playback technology element.",d),a.g.N=j,d;u.log(d)}}}n.play=function(){var a={type:"play",target:this.a};this.i(a);a.ia()||A(this,"play");return this};
n.pause=function(){A(this,"pause");return this};n.paused=function(){return z(this,"paused")===j?j:f};n.currentTime=function(a){return a!==c?(this.n.pc=a,A(this,"setCurrentTime",a),this.Ma&&this.i("timeupdate"),this):this.n.currentTime=z(this,"currentTime")||0};n.duration=function(a){return a!==c?(this.n.duration=parseFloat(a),this):this.n.duration};n.buffered=function(){var a=z(this,"buffered"),b=this.n.ya=this.n.ya||0;a&&(0<a.length&&a.end(0)!==b)&&(b=a.end(0),this.n.ya=b);return u.Ba(0,b)};
function ma(a){return a.duration()?a.buffered().end(0)/a.duration():0}n.volume=function(a){if(a!==c)return a=Math.max(0,Math.min(1,parseFloat(a))),this.n.volume=a,A(this,"setVolume",a),u.Yb(a),this;a=parseFloat(z(this,"volume"));return isNaN(a)?1:a};n.muted=function(a){return a!==c?(A(this,"setMuted",a),this):z(this,"muted")||j};n.ta=function(){return z(this,"supportsFullScreen")||j};
n.sa=function(){var a=u.Va.sa;this.D=f;a?(u.c(document,a.S,u.bind(this,function(){this.D=document[a.D];this.D===j&&u.o(document,a.S,arguments.callee);this.i("fullscreenchange")})),this.g.j.Ea===j&&this.f.flash.iFrameMode!==f&&(this.pause(),la(this),u.c(document,a.S,u.bind(this,function(){u.o(document,a.S,arguments.callee);ka(this,this.P,{src:this.n.src})}))),this.a[a.Ub]()):this.g.ta()?(this.i("fullscreenchange"),A(this,"enterFullScreen")):(this.i("fullscreenchange"),this.Jb=f,this.Gb=document.documentElement.style.overflow,
u.c(document,"keydown",u.bind(this,this.hb)),document.documentElement.style.overflow="hidden",u.m(document.body,"vjs-full-window"),u.m(this.a,"vjs-fullscreen"),this.i("enterFullWindow"));return this};function oa(a){var b=u.Va.sa;a.D=j;b?(a.g.j.Ea===j&&a.f.flash.iFrameMode!==f&&(a.pause(),la(a),u.c(document,b.S,u.bind(a,function(){u.o(document,b.S,arguments.callee);ka(this,this.P,{src:this.n.src})}))),document[b.Db]()):(a.g.ta()?A(a,"exitFullScreen"):pa(a),a.i("fullscreenchange"))}
n.hb=function(a){27===a.keyCode&&(this.D===f?oa(this):pa(this))};function pa(a){a.Jb=j;u.o(document,"keydown",a.hb);document.documentElement.style.overflow=a.Gb;u.s(document.body,"vjs-full-window");u.s(a.a,"vjs-fullscreen");a.i("exitFullWindow")}
n.src=function(a){if(a instanceof Array){var b;a:{b=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.M(e[d]),p=window.videojs[g];if(p.isSupported())for(var k=0,s=b;k<s.length;k++){var q=s[k];if(p.canPlaySource(q)){b={source:q,g:g};break a}}}b=j}b?(a=b.source,b=b.g,b==this.P?this.src(a):ka(this,b,a)):this.a.appendChild(u.d("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://www.google.com/chrome">Google Chrome</a> or download the latest <a href="http://get.adobe.com/flashplayer/">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.P].canPlaySource(a)?this.src(a.src):this.src([a]):(this.n.src=a,this.N?(A(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):y(this,function(){this.src(a)}));return this};n.load=function(){A(this,"load");return this};n.currentSrc=function(){return z(this,"currentSrc")||this.n.src||""};n.pa=function(a){return a!==c?(A(this,"setPreload",a),this.f.preload=a,this):z(this,"preload")};
n.autoplay=function(a){return a!==c?(A(this,"setAutoplay",a),this.f.autoplay=a,this):z(this,"autoplay")};n.loop=function(a){return a!==c?(A(this,"setLoop",a),this.f.loop=a,this):z(this,"loop")};n.poster=function(a){a!==c&&(this.nb=a);return this.nb};n.controls=function(a){a!==c&&(this.bb=a);return this.bb};n.error=function(){return z(this,"error")};var qa,ra,sa,ta;
if(document.lc!==c)qa="requestFullscreen",ra="exitFullscreen",sa="fullscreenchange",ta="fullScreen";else for(var ua=["moz","webkit"],va=ua.length-1;0<=va;va--){var B=ua[va];if(("moz"!=B||document.mozFullScreenEnabled)&&document[B+"CancelFullScreen"]!==c)qa=B+"RequestFullScreen",ra=B+"CancelFullScreen",sa=B+"fullscreenchange",ta="webkit"==B?B+"IsFullScreen":B+"FullScreen"}qa&&(u.Va.sa={Ub:qa,Db:ra,S:sa,D:ta});
function wa(a,b,d){x.call(this,a,b,d);if(!a.f.sources||0===a.f.sources.length){b=0;for(d=a.f.techOrder;b<d.length;b++){var e=u.M(d[b]),g=window.videojs[e];if(g&&g.isSupported()){ka(a,e);break}}}else a.src(a.f.sources)}t(wa,x);function C(a,b){x.call(this,a,b)}t(C,x);C.prototype.t=function(){return"vjs-control "+C.e.t.call(this)};
function D(a,b){x.call(this,a,b);a.F("play",u.bind(this,function(){var a,b=u.bind(this,this.$),g=u.bind(this,this.ga);this.$();"ontouchstart"in window||(this.b.c("mouseover",b),this.b.c("mouseout",g));a=j;this.b.c("touchstart",function(){a=f});this.b.c("touchmove",function(){a=j});this.b.c("touchend",u.bind(this,function(b){var e;a&&(e=this.l().className.search("fade-in"),-1!==e?this.ga():this.$());a=j;this.b.paused()||b.preventDefault()}))}))}t(D,x);n=D.prototype;
n.f={qc:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};n.d=function(){return u.d("div",{className:"vjs-control-bar"})};n.$=function(){D.e.$.call(this);this.b.i("controlsvisible")};n.ga=function(){D.e.ga.call(this);this.b.i("controlshidden")};n.lb=function(){this.a.style.opacity="1"};
function E(a,b){x.call(this,a,b);var d=j;this.c("touchstart",function(){d=f});this.c("touchmove",function(){d=j});var e=this;this.c("touchend",function(a){d&&e.k(a);a.preventDefault();a.stopPropagation()});this.c("click",this.k);this.c("focus",this.ma);this.c("blur",this.la)}t(E,C);n=E.prototype;
n.d=function(a,b){b=u.h.v({className:this.t(),innerHTML:'<div><span class="vjs-control-text">'+(this.L||"Need Text")+"</span></div>",Vb:"button","aria-live":"polite",tabIndex:0},b);return E.e.d.call(this,a,b)};n.k=function(){};n.ma=function(){u.c(document,"keyup",u.bind(this,this.O))};n.O=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.k()};n.la=function(){u.o(document,"keyup",u.bind(this,this.O))};function F(a,b){E.call(this,a,b)}t(F,E);F.prototype.L="Play";
F.prototype.t=function(){return"vjs-play-button "+F.e.t.call(this)};F.prototype.k=function(){this.b.play()};function G(a,b){E.call(this,a,b)}t(G,E);G.prototype.L="Play";G.prototype.t=function(){return"vjs-pause-button "+G.e.t.call(this)};G.prototype.k=function(){this.b.pause()};function xa(a,b){E.call(this,a,b);a.c("play",u.bind(this,this.Ra));a.c("pause",u.bind(this,this.Qa))}t(xa,E);n=xa.prototype;n.L="Play";n.t=function(){return"vjs-play-control "+xa.e.t.call(this)};
n.k=function(){this.b.paused()?this.b.play():this.b.pause()};n.Ra=function(){u.s(this.a,"vjs-paused");u.m(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};n.Qa=function(){u.s(this.a,"vjs-playing");u.m(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};function H(a,b){E.call(this,a,b)}t(H,E);H.prototype.L="Fullscreen";H.prototype.t=function(){return"vjs-fullscreen-control "+H.e.t.call(this)};
H.prototype.k=function(){this.b.D?(oa(this.b),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.b.sa(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};function I(a,b){E.call(this,a,b);a.c("play",u.bind(this,this.u))}t(I,E);I.prototype.d=function(){return I.e.d.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};I.prototype.k=function(){this.b.play()};
function ya(a,b){x.call(this,a,b);a.c("canplay",u.bind(this,this.u));a.c("canplaythrough",u.bind(this,this.u));a.c("playing",u.bind(this,this.u));a.c("seeked",u.bind(this,this.u));a.c("seeking",u.bind(this,this.show));a.c("seeked",u.bind(this,this.u));a.c("error",u.bind(this,this.show));a.c("waiting",u.bind(this,this.show))}t(ya,x);
ya.prototype.d=function(){var a,b;"string"==typeof this.b.l().style.WebkitBorderRadius||"string"==typeof this.b.l().style.MozBorderRadius||"string"==typeof this.b.l().style.jc||"string"==typeof this.b.l().style.kc?(a="vjs-loading-spinner",b='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",b="");return ya.e.d.call(this,
"div",{className:a,innerHTML:b})};function J(a,b){x.call(this,a,b);a.c("timeupdate",u.bind(this,this.ea))}t(J,x);J.prototype.d=function(){var a=J.e.d.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.d("div").appendChild(this.content));return a};
J.prototype.ea=function(){var a=this.b.Ua?this.b.n.currentTime:this.b.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.ha(a,this.b.duration())};function K(a,b){x.call(this,a,b);a.c("timeupdate",u.bind(this,this.ea))}t(K,x);
K.prototype.d=function(){var a=K.e.d.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(u.d("div").appendChild(this.content));return a};K.prototype.ea=function(){this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.ha(this.b.duration()))};
function za(a,b){x.call(this,a,b)}t(za,x);za.prototype.d=function(){return za.e.d.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};function L(a,b){x.call(this,a,b);a.c("timeupdate",u.bind(this,this.ea))}t(L,x);
L.prototype.d=function(){var a=L.e.d.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.d("div").appendChild(this.content));return a};
L.prototype.ea=function(){this.b.duration()&&this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.ha(this.b.duration()-this.b.currentTime()))};
function M(a,b){x.call(this,a,b);this.Bb=this.I[this.f.barName];this.handle=this.I[this.f.handleName];a.c(this.mb,u.bind(this,this.update));this.c("mousedown",this.na);this.c("touchstart",this.na);this.c("focus",this.ma);this.c("blur",this.la);this.b.c("controlsvisible",u.bind(this,this.update));y(a,u.bind(this,this.update));this.B={}}t(M,x);n=M.prototype;n.d=function(a,b){b=u.h.v({Vb:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},b);return M.e.d.call(this,a,b)};
n.na=function(a){a.preventDefault();u.Cb();this.B.move=u.bind(this,this.Oa);this.B.end=u.bind(this,this.Pa);u.c(document,"mousemove",this.B.move);u.c(document,"mouseup",this.B.end);u.c(document,"touchmove",this.B.move);u.c(document,"touchend",this.B.end);this.Oa(a)};n.Pa=function(){u.dc();u.o(document,"mousemove",this.B.move,j);u.o(document,"mouseup",this.B.end,j);u.o(document,"touchmove",this.B.move,j);u.o(document,"touchend",this.B.end,j);this.update()};
n.update=function(){if(this.a){var a,b=this.Ga(),d=this.handle,e=this.Bb;isNaN(b)&&(b=0);a=b;if(d){a=this.a.offsetWidth;var g=d.l().offsetWidth;a=g?g/a:0;b*=1-a;a=b+a/2;d.l().style.left=u.round(100*b,2)+"%"}e.l().style.width=u.round(100*a,2)+"%"}};function Aa(a,b){var d=a.a,e=u.Ib(d),d=d.offsetWidth,g=a.handle,p=b.pageX;g&&(g=g.l().offsetWidth,e+=g/2,d-=g);0===p&&b.changedTouches&&(p=b.changedTouches[0].pageX);return Math.max(0,Math.min(1,(p-e)/d))}
n.ma=function(){u.c(document,"keyup",u.bind(this,this.O))};n.O=function(a){37==a.which?(a.preventDefault(),this.qb()):39==a.which&&(a.preventDefault(),this.rb())};n.la=function(){u.o(document,"keyup",u.bind(this,this.O))};function N(a,b){x.call(this,a,b)}t(N,x);N.prototype.f={children:{seekBar:{}}};N.prototype.d=function(){return N.e.d.call(this,"div",{className:"vjs-progress-control vjs-control"})};
function O(a,b){M.call(this,a,b);a.c("timeupdate",u.bind(this,this.da));y(a,u.bind(this,this.da))}t(O,M);n=O.prototype;n.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};n.mb="timeupdate";n.d=function(){return O.e.d.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
n.da=function(){var a=this.b.Ua?this.b.n.currentTime:this.b.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.Ga(),2));this.a.setAttribute("aria-valuetext",u.ha(a,this.b.duration()))};n.Ga=function(){return this.b.currentTime()/this.b.duration()};n.na=function(a){O.e.na.call(this,a);this.b.Ua=f;this.ec=!this.b.paused();this.b.pause()};n.Oa=function(a){a=Aa(this,a)*this.b.duration();a==this.b.duration()&&(a-=0.1);this.b.currentTime(a)};
n.Pa=function(a){O.e.Pa.call(this,a);this.b.Ua=j;this.ec&&this.b.play()};n.rb=function(){this.b.currentTime(this.b.currentTime()+5)};n.qb=function(){this.b.currentTime(this.b.currentTime()-5)};function P(a,b){x.call(this,a,b);a.c("progress",u.bind(this,this.update))}t(P,x);P.prototype.d=function(){return P.e.d.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
P.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*ma(this.b),2)+"%")};function Ba(a,b){x.call(this,a,b)}t(Ba,x);Ba.prototype.d=function(){return Ba.e.d.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};function Ca(a,b){x.call(this,a,b)}t(Ca,x);Ca.prototype.d=function(){return Ca.e.d.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};
function Da(a,b){x.call(this,a,b);a.g&&(a.g.j&&a.g.j.V===j)&&this.m("vjs-hidden");a.c("loadstart",u.bind(this,function(){a.g.j&&a.g.j.V===j?this.m("vjs-hidden"):this.s("vjs-hidden")}))}t(Da,x);Da.prototype.f={children:{volumeBar:{}}};Da.prototype.d=function(){return Da.e.d.call(this,"div",{className:"vjs-volume-control vjs-control"})};function Ea(a,b){M.call(this,a,b);a.c("volumechange",u.bind(this,this.da));y(a,u.bind(this,this.da));setTimeout(u.bind(this,this.update),0)}t(Ea,M);n=Ea.prototype;
n.da=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.b.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.b.volume(),2)+"%")};n.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};n.mb="volumechange";n.d=function(){return Ea.e.d.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};n.Oa=function(a){this.b.volume(Aa(this,a))};n.Ga=function(){return this.b.volume()};
n.rb=function(){this.b.volume(this.b.volume()+0.1)};n.qb=function(){this.b.volume(this.b.volume()-0.1)};function Fa(a,b){x.call(this,a,b)}t(Fa,x);Fa.prototype.d=function(){return Fa.e.d.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};function Ga(a,b){x.call(this,a,b)}t(Ga,x);Ga.prototype.d=function(){return Ga.e.d.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};
function Q(a,b){E.call(this,a,b);a.c("volumechange",u.bind(this,this.update));a.g&&(a.g.j&&a.g.j.V===j)&&this.m("vjs-hidden");a.c("loadstart",u.bind(this,function(){a.g.j&&a.g.j.V===j?this.m("vjs-hidden"):this.s("vjs-hidden")}))}t(Q,E);Q.prototype.d=function(){return Q.e.d.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};Q.prototype.k=function(){this.b.muted(this.b.muted()?j:f)};
Q.prototype.update=function(){var a=this.b.volume(),b=3;0===a||this.b.muted()?b=0:0.33>a?b=1:0.67>a&&(b=2);this.b.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.s(this.a,"vjs-vol-"+a);u.m(this.a,"vjs-vol-"+b)};function Ha(a,b){E.call(this,a,b);a.poster()||this.u();a.c("play",u.bind(this,this.u))}t(Ha,E);
Ha.prototype.d=function(){var a=u.d("div",{className:"vjs-poster",tabIndex:-1}),b=this.b.poster();b&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+b+'")':a.appendChild(u.d("img",{src:b})));return a};Ha.prototype.k=function(){this.b.play()};function R(a,b){x.call(this,a,b)}t(R,x);function Ia(a,b){a.K(b);b.c("click",u.bind(a,function(){ha(this)}))}R.prototype.d=function(){return R.e.d.call(this,"ul",{className:"vjs-menu"})};
function S(a,b){E.call(this,a,b);b.selected?(this.m("vjs-selected"),this.a.setAttribute("aria-selected",f)):this.a.setAttribute("aria-selected",j)}t(S,E);S.prototype.d=function(a,b){return S.e.d.call(this,"li",u.h.v({className:"vjs-menu-item",innerHTML:this.f.label},b))};S.prototype.k=function(){this.selected(f)};S.prototype.selected=function(a){a?(this.m("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.s("vjs-selected"),this.a.setAttribute("aria-selected",j))};
function T(a,b,d){x.call(this,a,b,d)}t(T,x);T.prototype.k=function(){this.b.controls()&&(this.b.paused()?this.b.play():this.b.pause())};T.prototype.j={V:f,Ea:j,Ta:j,Wa:j};u.media={};u.media.va="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function Ja(){var a=u.media.va[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.va.length-1;0<=i;i--)T.prototype[u.media.va[i]]=Ja();
function U(a,b,d){x.call(this,a,b,d);d=this.j;var e=u.wa.volume;u.wa.volume=e/2+0.1;d.V=e!==u.wa.volume;(b=b.source)&&this.a.currentSrc==b.src?a.i("loadstart"):b&&(this.a.src=b.src);y(a,function(){this.f.autoplay&&this.paused()&&(this.G.poster=h,this.play())});this.c("click",this.k);for(a=Ka.length-1;0<=a;a--)u.c(this.a,Ka[a],u.bind(this.b,this.Hb));this.ua()}t(U,T);n=U.prototype;n.z=function(){U.e.z.call(this)};
n.d=function(){var a=this.b,b=a.G;if(!b||La===j)b?(a.l().removeChild(b),b=b.cloneNode(j)):b=u.d("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),b.player=a,u.Ha(b,a.l());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(b[g]=a.f[g])}return b};n.Hb=function(a){"play"!==a.type&&(this.i(a),a.stopPropagation())};n.play=function(){this.a.play()};n.pause=function(){this.a.pause()};n.paused=function(){return this.a.paused};n.currentTime=function(){return this.a.currentTime};
n.Xb=function(a){try{this.a.currentTime=a}catch(b){u.log(b,"Video is not ready. (Video.js)")}};n.duration=function(){return this.a.duration||0};n.buffered=function(){return this.a.buffered};n.volume=function(){return this.a.volume};n.bc=function(a){this.a.volume=a};n.muted=function(){return this.a.muted};n.$b=function(a){this.a.muted=a};n.width=function(){return this.a.offsetWidth};n.height=function(){return this.a.offsetHeight};
n.ta=function(){return"function"==typeof this.a.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:j};n.src=function(a){this.a.src=a};n.load=function(){this.a.load()};n.currentSrc=function(){return this.a.currentSrc};n.pa=function(){return this.a.pa};n.ac=function(a){this.a.pa=a};n.autoplay=function(){return this.a.autoplay};n.Wb=function(a){this.a.autoplay=a};n.loop=function(){return this.a.loop};n.Zb=function(a){this.a.loop=a};n.error=function(){return this.a.error};
var Ka="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" "),La=!u.wb;u.ub&&3>u.tb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
function V(a,b,d){x.call(this,a,b,d);this.j.rc=!u.H.match("Firefox");var e=b.source,g=b.parentEl;d=this.a=u.d("div",{id:a.id()+"_temp_flash"});var p=a.id()+"_flash_api";a=a.f;var k=u.h.v({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.pa,loop:a.loop,muted:a.muted},b.flashVars),s=u.h.v({wmode:"opaque",bgcolor:"#000000"},b.params),q=u.h.v({id:p,name:p,"class":"vjs-tech"},b.attributes);e&&
(k.src=encodeURIComponent(u.ib(e.src)));u.Ha(d,g);b.startTime&&y(this,function(){this.load();this.play();this.currentTime(b.startTime)});if(b.iFrameMode===f&&!u.vb){var w=u.d("iframe",{id:p+"_iframe",name:p+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.c(w,"load",u.bind(this,function(){var a,d=w.contentWindow;a=w.contentDocument?w.contentDocument:w.contentWindow.document;
a.write(Ma(b.swf,k,s,q));d.player=this.b;d.ready=u.bind(this.b,function(b){b=a.getElementById(b);var d=this.g;d.a=b;u.c(b,"click",d.bind(d.k));Na(d)});d.events=u.bind(this.b,function(a,b){this&&"flash"===this.P&&this.i(b)});d.errors=u.bind(this.b,function(a,b){u.log("Flash Error",b)})}));d.parentNode.replaceChild(w,d)}else{a=Ma(b.swf,k,s,q);a=u.d("div",{innerHTML:a}).childNodes[0];e=d.parentNode;d.parentNode.replaceChild(a,d);var gb=e.childNodes[0];setTimeout(function(){gb.style.display="block"},
1E3)}}t(V,T);n=V.prototype;n.z=function(){V.e.z.call(this)};n.play=function(){this.a.vjs_play()};n.pause=function(){this.a.vjs_pause()};n.src=function(a){a=u.ib(a);this.a.vjs_src(a);if(this.b.autoplay()){var b=this;setTimeout(function(){b.play()},0)}};n.load=function(){this.a.vjs_load()};n.poster=function(){this.a.vjs_getProperty("poster")};n.buffered=function(){return u.Ba(0,this.a.vjs_getProperty("buffered"))};n.ta=m(j);
var Oa=V.prototype,Pa="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),Qa="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function Ra(){var a=Pa[W],b=a.charAt(0).toUpperCase()+a.slice(1);Oa["set"+b]=function(b){return this.a.vjs_setProperty(a,b)}}
function Sa(a){Oa[a]=function(){return this.a.vjs_getProperty(a)}}var W;for(W=0;W<Pa.length;W++)Sa(Pa[W]),Ra();for(W=0;W<Qa.length;W++)Sa(Qa[W]);var Ta={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};V.onReady=function(a){a=u.l(a);var b=a.player||a.parentNode.player,d=b.g;a.player=b;d.a=a;d.c("click",d.k);Na(d)};function Na(a){a.l().vjs_getProperty?a.ua():setTimeout(function(){Na(a)},50)}V.onEvent=function(a,b){"play"!==b&&u.l(a).player.i(b)};
V.onError=function(a,b){u.l(a).player.i("error");u.log("Flash Error",b,a)};function Ma(a,b,d,e){var g="",p="",k="";b&&u.h.Y(b,function(a,b){g+=a+"="+b+"&amp;"});d=u.h.v({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.h.Y(d,function(a,b){p+='<param name="'+a+'" value="'+b+'" />'});e=u.h.v({data:a,width:"100%",height:"100%"},e);u.h.Y(e,function(a,b){k+=a+'="'+b+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+p+"</object>"}
function X(a){a.ca=a.ca||[];return a.ca}function Ua(a,b,d){for(var e=a.ca,g=0,p=e.length,k,s;g<p;g++)k=e[g],k.id()===b?(k.show(),s=k):d&&(k.A()==d&&0<k.mode())&&k.disable();(b=s?s.A():d?d:j)&&a.i(b+"trackchange")}function Y(a,b){x.call(this,a,b);this.C=b.id||"vjs_"+b.kind+"_"+b.language+"_"+u.p++;this.pb=b.src;this.Eb=b["default"]||b.dflt;this.tc=b.title;this.oc=b.srclang;this.Kb=b.label;this.R=[];this.Za=[];this.T=this.U=0;this.b.c("fullscreenchange",u.bind(this,this.Ab))}t(Y,x);n=Y.prototype;
n.A=l("r");n.src=l("pb");n.Ca=l("Eb");n.label=l("Kb");n.readyState=l("U");n.mode=l("T");n.Ab=function(){this.a.style.fontSize=this.b.D?140*(screen.width/this.b.width())+"%":""};n.d=function(){return Y.e.d.call(this,"div",{className:"vjs-"+this.r+" vjs-text-track"})};n.show=function(){Va(this);this.T=2;Y.e.show.call(this)};n.u=function(){Va(this);this.T=1;Y.e.u.call(this)};
n.disable=function(){2==this.T&&this.u();this.b.o("timeupdate",u.bind(this,this.update,this.C));this.b.o("ended",u.bind(this,this.reset,this.C));this.reset();this.b.I.textTrackDisplay.removeChild(this);this.T=0};function Va(a){0===a.U&&a.load();0===a.T&&(a.b.c("timeupdate",u.bind(a,a.update,a.C)),a.b.c("ended",u.bind(a,a.reset,a.C)),("captions"===a.r||"subtitles"===a.r)&&a.b.I.textTrackDisplay.K(a))}n.load=function(){0===this.U&&(this.U=1,u.get(this.pb,u.bind(this,this.Rb),u.bind(this,this.Na)))};
n.Na=function(a){this.error=a;this.U=3;this.i("error")};n.Rb=function(a){var b,d;a=a.split("\n");for(var e="",g=1,p=a.length;g<p;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(b=e,e=u.trim(a[++g])):b=this.R.length;b={id:b,index:this.R.length};d=e.split(" --\x3e ");b.startTime=Wa(d[0]);b.Z=Wa(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);b.text=d.join("<br/>");this.R.push(b)}this.U=2;this.i("loaded")};
function Wa(a){var b=a.split(":");a=0;var d,e,g;3==b.length?(d=b[0],e=b[1],b=b[2]):(d=0,e=b[0],b=b[1]);b=b.split(/\s+/);b=b.splice(0,1)[0];b=b.split(/\.|,/);g=parseFloat(b[1]);b=b[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(b);g&&(a+=g/1E3);return a}
n.update=function(){if(0<this.R.length){var a=this.b.currentTime();if(this.Sa===c||a<this.Sa||this.ka<=a){var b=this.R,d=this.b.duration(),e=0,g=j,p=[],k,s,q,w;a>=this.ka||this.ka===c?w=this.Da!==c?this.Da:0:(g=f,w=this.Ka!==c?this.Ka:b.length-1);for(;;){q=b[w];if(q.Z<=a)e=Math.max(e,q.Z),q.fa&&(q.fa=j);else if(a<q.startTime){if(d=Math.min(d,q.startTime),q.fa&&(q.fa=j),!g)break}else g?(p.splice(0,0,q),s===c&&(s=w),k=w):(p.push(q),k===c&&(k=w),s=w),d=Math.min(d,q.Z),e=Math.max(e,q.startTime),q.fa=
f;if(g)if(0===w)break;else w--;else if(w===b.length-1)break;else w++}this.Za=p;this.ka=d;this.Sa=e;this.Da=k;this.Ka=s;a=this.Za;b="";d=0;for(e=a.length;d<e;d++)b+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=b;this.i("cuechange")}}};n.reset=function(){this.ka=0;this.Sa=this.b.duration();this.Ka=this.Da=0};function Xa(a,b){Y.call(this,a,b)}t(Xa,Y);Xa.prototype.r="captions";function Ya(a,b){Y.call(this,a,b)}t(Ya,Y);Ya.prototype.r="subtitles";function Za(a,b){Y.call(this,a,b)}
t(Za,Y);Za.prototype.r="chapters";function $a(a,b,d){x.call(this,a,b,d);if(a.f.tracks&&0<a.f.tracks.length){b=this.b;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=b,p=e.kind,k=e.label,s=e.language,q=e;e=g.ca=g.ca||[];q=q||{};q.kind=p;q.label=k;q.language=s;p=u.M(p||"subtitles");g=new window.videojs[p+"Track"](g,q);e.push(g)}}}t($a,x);$a.prototype.d=function(){return $a.e.d.call(this,"div",{className:"vjs-text-track-display"})};
function Z(a,b){var d=this.Q=b.track;b.label=d.label();b.selected=d.Ca();S.call(this,a,b);this.b.c(d.A()+"trackchange",u.bind(this,this.update))}t(Z,S);Z.prototype.k=function(){Z.e.k.call(this);Ua(this.b,this.Q.C,this.Q.A())};Z.prototype.update=function(){2==this.Q.mode()?this.selected(f):this.selected(j)};function ab(a,b){b.track={A:function(){return b.kind},Sb:a,label:m("Off"),Ca:m(j),mode:m(j)};Z.call(this,a,b);this.selected(f)}t(ab,Z);
ab.prototype.k=function(){ab.e.k.call(this);Ua(this.b,this.Q.C,this.Q.A())};ab.prototype.update=function(){for(var a=X(this.b),b=0,d=a.length,e,g=f;b<d;b++)e=a[b],e.A()==this.Q.A()&&2==e.mode()&&(g=j);g?this.selected(f):this.selected(j)};function $(a,b){E.call(this,a,b);this.ja=this.Aa();0===this.aa.length&&this.u();this.c("keyup",this.O);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}t($,E);n=$.prototype;n.W=j;
n.Aa=function(){var a=new R(this.b);a.l().appendChild(u.d("li",{className:"vjs-menu-title",innerHTML:u.M(this.r),cc:-1}));Ia(a,new ab(this.b,{kind:this.r}));this.aa=this.cb();for(var b=0;b<this.aa.length;b++)Ia(a,this.aa[b]);this.K(a);return a};n.cb=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.A()===this.r&&a.push(new Z(this.b,{track:b}));return a};n.t=function(){return this.className+" vjs-menu-button "+$.e.t.call(this)};n.ma=function(){};n.la=function(){};
n.k=function(){this.F("mouseout",u.bind(this,function(){ha(this.ja);this.a.blur()}));this.W?bb(this):cb(this)};n.O=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.W?bb(this):cb(this);27==a.which&&(a.preventDefault(),this.W&&bb(this))};function cb(a){a.W=f;a.ja.lb();a.a.setAttribute("aria-pressed",f);a.a.children[1].children[0].focus()}function bb(a){a.W=j;ha(a.ja);a.a.setAttribute("aria-pressed",j)}
function db(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Captions Menu")}t(db,$);db.prototype.r="captions";db.prototype.L="Captions";db.prototype.className="vjs-captions-button";function eb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Subtitles Menu")}t(eb,$);eb.prototype.r="subtitles";eb.prototype.L="Subtitles";eb.prototype.className="vjs-subtitles-button";function fb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Chapters Menu")}t(fb,$);n=fb.prototype;n.r="chapters";
n.L="Chapters";n.className="vjs-chapters-button";n.cb=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.A()===this.r&&a.push(new Z(this.b,{track:b}));return a};
n.Aa=function(){for(var a=X(this.b),b=0,d=a.length,e,g,p=this.aa=[];b<d;b++)if(e=a[b],e.A()==this.r&&e.Ca()){if(2>e.readyState()){this.mc=e;e.c("loaded",u.bind(this,this.Aa));return}g=e;break}a=this.ja=new R(this.b);a.a.appendChild(u.d("li",{className:"vjs-menu-title",innerHTML:u.M(this.r),cc:-1}));if(g){e=g.R;for(var k,b=0,d=e.length;b<d;b++)k=e[b],k=new hb(this.b,{track:g,cue:k}),p.push(k),a.K(k)}this.K(a);0<this.aa.length&&this.show();return a};
function hb(a,b){var d=this.Q=b.track,e=this.cue=b.cue,g=a.currentTime();b.label=e.text;b.selected=e.startTime<=g&&g<e.Z;S.call(this,a,b);d.c("cuechange",u.bind(this,this.update))}t(hb,S);hb.prototype.k=function(){hb.e.k.call(this);this.b.currentTime(this.cue.startTime);this.update(this.cue.startTime)};hb.prototype.update=function(){var a=this.cue,b=this.b.currentTime();a.startTime<=b&&b<a.Z?this.selected(f):this.selected(j)};u.h.v(D.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var ib=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,b){function d(a,e){var k,s,q=a[e];if(q&&"object"===typeof q)for(k in q)Object.prototype.hasOwnProperty.call(q,k)&&(s=d(q,k),s!==c?q[k]=s:delete q[k]);return b.call(a,e,q)}var e;a=String(a);ib.lastIndex=0;ib.test(a)&&(a=a.replace(ib,function(a){return"\\u"+("0000"+
a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.xa=function(){var a,b,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((b=d[e])&&b.getAttribute)b.player===c&&(a=b.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),ba(b,a)));else{u.$a();break}else u.gc||u.$a()};u.$a=function(){setTimeout(u.xa,1)};u.F(window,"load",function(){u.gc=f});u.xa();u.Tb=function(a,b){v.prototype[a]=b};r("videojs",u);r("_V_",u);r("videojs.options",u.options);r("videojs.cache",u.X);r("videojs.Component",x);
x.prototype.dispose=x.prototype.z;x.prototype.createEl=x.prototype.d;x.prototype.el=x.prototype.l;x.prototype.addChild=x.prototype.K;x.prototype.children=x.prototype.children;x.prototype.on=x.prototype.c;x.prototype.off=x.prototype.o;x.prototype.one=x.prototype.F;x.prototype.trigger=x.prototype.i;x.prototype.triggerReady=x.prototype.ua;x.prototype.show=x.prototype.show;x.prototype.hide=x.prototype.u;x.prototype.width=x.prototype.width;x.prototype.height=x.prototype.height;x.prototype.dimensions=x.prototype.Fb;
r("videojs.Player",v);r("videojs.MediaLoader",wa);r("videojs.TextTrackDisplay",$a);r("videojs.Control",C);r("videojs.ControlBar",D);r("videojs.Button",E);r("videojs.PlayButton",F);r("videojs.PauseButton",G);r("videojs.PlayToggle",xa);r("videojs.FullscreenToggle",H);r("videojs.BigPlayButton",I);r("videojs.LoadingSpinner",ya);r("videojs.CurrentTimeDisplay",J);r("videojs.DurationDisplay",K);r("videojs.TimeDivider",za);r("videojs.RemainingTimeDisplay",L);r("videojs.Slider",M);
r("videojs.ProgressControl",N);r("videojs.SeekBar",O);r("videojs.LoadProgressBar",P);r("videojs.PlayProgressBar",Ba);r("videojs.SeekHandle",Ca);r("videojs.VolumeControl",Da);r("videojs.VolumeBar",Ea);r("videojs.VolumeLevel",Fa);r("videojs.VolumeHandle",Ga);r("videojs.MuteToggle",Q);r("videojs.PosterImage",Ha);r("videojs.Menu",R);r("videojs.MenuItem",S);r("videojs.SubtitlesButton",eb);r("videojs.CaptionsButton",db);r("videojs.ChaptersButton",fb);r("videojs.MediaTechController",T);
T.prototype.features=T.prototype.j;T.prototype.j.volumeControl=T.prototype.j.V;T.prototype.j.fullscreenResize=T.prototype.j.Ea;T.prototype.j.progressEvents=T.prototype.j.Ta;T.prototype.j.timeupdateEvents=T.prototype.j.Wa;r("videojs.Html5",U);U.Events=Ka;U.isSupported=function(){return!!document.createElement("video").canPlayType};U.canPlaySource=function(a){return!!document.createElement("video").canPlayType(a.type)};U.prototype.setCurrentTime=U.prototype.Xb;U.prototype.setVolume=U.prototype.bc;
U.prototype.setMuted=U.prototype.$b;U.prototype.setPreload=U.prototype.ac;U.prototype.setAutoplay=U.prototype.Wb;U.prototype.setLoop=U.prototype.Zb;r("videojs.Flash",V);
V.isSupported=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(b){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return 10<=a.split(",")[0]};V.canPlaySource=function(a){if(a.type in Ta)return"maybe"};
V.onReady=V.onReady;r("videojs.TextTrack",Y);Y.prototype.label=Y.prototype.label;r("videojs.CaptionsTrack",Xa);r("videojs.SubtitlesTrack",Ya);r("videojs.ChaptersTrack",Za);r("videojs.autoSetup",u.xa);r("videojs.plugin",u.Tb);r("videojs.createTimeRange",u.Ba);
