(function() {var b=void 0,f=!0,h=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function r(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.Ga[a])return u.Ga[a];a=u.o(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.ba(a,c,d)}var v=u;window.td=window.ud=u;u.Cb="GENERATED_CDN_VSN";
u.Bb="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{swf:u.Bb+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.Ga={};"GENERATED_CDN_VSN"!=u.Cb&&(v.options.flash.swf=u.Bb+"vjs.zencdn.net/"+u.Cb+"/video-js.swf");u.ga=u.CoreObject=m();
u.ga.extend=function(a){var c,d;a=a||{};c=a.init||a.f||this.prototype.init||this.prototype.f||m();d=function(){c.apply(this,arguments)};d.prototype=u.i.create(this.prototype);d.prototype.constructor=d;d.extend=u.ga.extend;d.create=u.ga.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.ga.create=function(){var a=u.i.create(this.prototype);this.apply(a,arguments);return a};
u.d=function(a,c,d){var e=u.getData(a);e.w||(e.w={});e.w[c]||(e.w[c]=[]);d.u||(d.u=u.u++);e.w[c].push(d);e.Q||(e.disabled=l,e.Q=function(c){if(!e.disabled){c=u.Yb(c);var d=e.w[c.type];if(d)for(var d=d.slice(0),k=0,q=d.length;k<q&&!c.dc();k++)d[k].call(a,c)}});1==e.w[c].length&&(document.addEventListener?a.addEventListener(c,e.Q,l):document.attachEvent&&a.attachEvent("on"+c,e.Q))};
u.t=function(a,c,d){if(u.cc(a)){var e=u.getData(a);if(e.w)if(c){var g=e.w[c];if(g){if(d){if(d.u)for(e=0;e<g.length;e++)g[e].u===d.u&&g.splice(e--,1)}else e.w[c]=[];u.Tb(a,c)}}else for(g in e.w)c=g,e.w[c]=[],u.Tb(a,c)}};u.Tb=function(a,c){var d=u.getData(a);0===d.w[c].length&&(delete d.w[c],document.removeEventListener?a.removeEventListener(c,d.Q,l):document.detachEvent&&a.detachEvent("on"+c,d.Q));u.ob(d.w)&&(delete d.w,delete d.Q,delete d.disabled);u.ob(d)&&u.kc(a)};
u.Yb=function(a){function c(){return f}function d(){return l}if(!a||!a.pb){var e=a||window.event;a={};for(var g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.nb=c};a.nb=d;a.stopPropagation=function(){e.stopPropagation&&e.stopPropagation();a.cancelBubble=f;a.pb=c};a.pb=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&e.stopImmediatePropagation();
a.dc=c;a.stopPropagation()};a.dc=d;if(a.clientX!=h){g=document.documentElement;var j=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||j&&j.scrollLeft||0)-(g&&g.clientLeft||j&&j.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||j&&j.scrollTop||0)-(g&&g.clientTop||j&&j.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.j=function(a,c){var d=u.cc(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.Yb(c);d.Q&&d.Q.call(a,c);if(e&&!c.pb())u.j(e,c);else if(!e&&!c.nb()&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.nb()};u.O=function(a,c,d){u.d(a,c,function(){u.t(a,c,arguments.callee);d.apply(this,arguments)})};var w=Object.prototype.hasOwnProperty;
u.e=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)w.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.W=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.i={};u.i.create=Object.create||function(a){function c(){}c.prototype=a;return new c};u.i.ka=function(a,c,d){for(var e in a)w.call(a,e)&&c.call(d||this,e,a[e])};u.i.B=function(a,c){if(!c)return a;for(var d in c)w.call(c,d)&&(a[d]=c[d]);return a};
u.i.Xb=function(a,c){var d,e,g;a=u.i.copy(a);for(d in c)w.call(c,d)&&(e=a[d],g=c[d],a[d]=u.i.ec(e)&&u.i.ec(g)?u.i.Xb(e,g):c[d]);return a};u.i.copy=function(a){return u.i.B({},a)};u.i.ec=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.u||(c.u=u.u++);e.u=d?d+"_"+c.u:c.u;return e};u.ja={};u.u=1;u.expando="vdata"+(new Date).getTime();
u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.u++,u.ja[c]={});return u.ja[c]};u.cc=function(a){a=a[u.expando];return!(!a||u.ob(u.ja[a]))};u.kc=function(a){var c=a[u.expando];if(c){delete u.ja[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.ob=function(a){for(var c in a)if(a[c]!==h)return l;return f};u.q=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
u.v=function(a,c){if(-1!=a.className.indexOf(c)){for(var d=a.className.split(" "),e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};u.Za=u.e("video");u.U=navigator.userAgent;u.vc=!!u.U.match(/iPhone/i);u.uc=!!u.U.match(/iPad/i);u.wc=!!u.U.match(/iPod/i);u.tc=u.vc||u.uc||u.wc;var aa=u,x;var y=u.U.match(/OS (\d+)_/i);x=y&&y[1]?y[1]:b;aa.jd=x;u.rc=!!u.U.match(/Android.*AppleWebKit/i);var ba=u,z=u.U.match(/Android (\d+)\./i);ba.qc=z&&z[1]?z[1]:h;u.sc=function(){return!!u.U.match("Firefox")};
u.kb=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,j=d.length-1;0<=j;j--){e=d[j].name;g=d[j].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:l;c[e]=g}return c};u.od=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};
u.mb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Ab={};u.o=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};u.Aa=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),j=Math.floor(c/60%60),k=Math.floor(c/3600),g=0<g||0<k?g+":":"";return g+(((g||10<=j)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Ac=function(){document.body.focus();document.onselectstart=r(l)};u.ed=function(){document.onselectstart=r(f)};
u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};u.hb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(j){d(j)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.Zc=function(a){var c=window.localStorage||l;if(c)try{c.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.ac=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Ic="getBoundingClientRect"in document.documentElement?function(a){var c;try{c=a.getBoundingClientRect()}catch(d){}if(!c)return 0;a=document.body;return c.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var c=a.offsetLeft;a=a.offsetParent;)c+=a.offsetLeft;return c};
u.c=u.ga.extend({f:function(a,c,d){this.a=a;this.g=u.i.copy(this.g);c=this.options(c);this.J=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.u++);this.Nc=c.name||h;this.b=c.el||this.e();this.D=[];this.fb={};this.P={};if((a=this.g)&&a.children){var e=this;u.i.ka(a.children,function(a,c){c!==l&&!c.loadEvent&&(e[a]=e.V(a,c))})}this.K(d)}});t=u.c.prototype;
t.C=function(){if(this.D)for(var a=this.D.length-1;0<=a;a--)this.D[a].C&&this.D[a].C();this.P=this.fb=this.D=h;this.t();this.b.parentNode&&this.b.parentNode.removeChild(this.b);u.kc(this.b);this.b=h};t.gc=p("a");t.options=function(a){return a===b?this.g:this.g=u.i.Xb(this.g,a)};t.e=function(a,c){return u.e(a,c)};t.o=p("b");t.id=p("J");t.name=p("Nc");t.children=p("D");
t.V=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.W(e),c.name=e,d=new window.videojs[d](this.a||this,c)):d=a;this.D.push(d);"function"===typeof d.id&&(this.fb[d.id()]=d);(e=e||d.name&&d.name())&&(this.P[e]=d);"function"===typeof d.el&&d.el()&&this.b.appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.P[a]);if(a&&this.D){for(var c=l,d=this.D.length-1;0<=d;d--)if(this.D[d]===a){c=f;this.D.splice(d,1);break}c&&(this.fb[a.id]=h,this.P[a.name]=h,(c=a.o())&&c.parentNode===this.b&&this.b.removeChild(a.o()))}};t.M=r("");t.d=function(a,c){u.d(this.b,a,u.bind(this,c));return this};t.t=function(a,c){u.t(this.b,a,c);return this};t.O=function(a,c){u.O(this.b,a,u.bind(this,c));return this};t.j=function(a,c){u.j(this.b,a,c);return this};
t.K=function(a){a&&(this.X?a.call(this):(this.Ja===b&&(this.Ja=[]),this.Ja.push(a)));return this};t.Ma=function(){this.X=f;var a=this.Ja;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Ja=[];this.j("ready")}};t.q=function(a){u.q(this.b,a);return this};t.v=function(a){u.v(this.b,a);return this};t.show=function(){this.b.style.display="block";return this};t.A=function(){this.b.style.display="none";return this};t.ma=function(){this.v("vjs-fade-out");this.q("vjs-fade-in");return this};
t.za=function(){this.v("vjs-fade-in");this.q("vjs-fade-out");return this};t.fc=function(){this.q("vjs-lock-showing");return this};t.Na=function(){this.v("vjs-lock-showing");return this};t.width=function(a,c){return A(this,"width",a,c)};t.height=function(a,c){return A(this,"height",a,c)};t.Ec=function(a,c){return this.width(a,f).height(c)};
function A(a,c,d,e){if(d!==b)return a.b.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.j("resize"),a;if(!a.b)return 0;d=a.b.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.b["offset"+u.W(c)],10)}
u.n=u.c.extend({f:function(a,c){u.c.call(this,a,c);var d=l;this.d("touchstart",function(){d=f});this.d("touchmove",function(){d=l});var e=this;this.d("touchend",function(a){d&&e.r(a);a.preventDefault();a.stopPropagation()});this.d("click",this.r);this.d("focus",this.Ea);this.d("blur",this.Da)}});t=u.n.prototype;
t.e=function(a,c){c=u.i.B({className:this.M(),innerHTML:'<div><span class="vjs-control-text">'+(this.ia||"Need Text")+"</span></div>",Wc:"button","aria-live":"polite",tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.M=function(){return"vjs-control "+u.c.prototype.M.call(this)};t.r=m();t.Ea=function(){u.d(document,"keyup",u.bind(this,this.Y))};t.Y=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.r()};t.Da=function(){u.t(document,"keyup",u.bind(this,this.Y))};
u.H=u.c.extend({f:function(a,c){u.c.call(this,a,c);this.zc=this.P[this.g.barName];this.handle=this.P[this.g.handleName];a.d(this.hc,u.bind(this,this.update));this.d("mousedown",this.Fa);this.d("touchstart",this.Fa);this.d("focus",this.Ea);this.d("blur",this.Da);this.a.d("controlsvisible",u.bind(this,this.update));a.K(u.bind(this,this.update));this.I={}}});t=u.H.prototype;
t.e=function(a,c){c=u.i.B({Wc:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.Fa=function(a){a.preventDefault();u.Ac();this.I.move=u.bind(this,this.ub);this.I.end=u.bind(this,this.vb);u.d(document,"mousemove",this.I.move);u.d(document,"mouseup",this.I.end);u.d(document,"touchmove",this.I.move);u.d(document,"touchend",this.I.end);this.ub(a)};
t.vb=function(){u.ed();u.t(document,"mousemove",this.I.move,l);u.t(document,"mouseup",this.I.end,l);u.t(document,"touchmove",this.I.move,l);u.t(document,"touchend",this.I.end,l);this.update()};t.update=function(){if(this.b){var a,c=this.lb(),d=this.handle,e=this.zc;isNaN(c)&&(c=0);a=c;if(d){a=this.b.offsetWidth;var g=d.o().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.o().style.left=u.round(100*c,2)+"%"}e.o().style.width=u.round(100*a,2)+"%"}};
function B(a,c){var d=a.b,e=u.Ic(d),d=d.offsetWidth,g=a.handle,j=c.pageX;g&&(g=g.o().offsetWidth,e+=g/2,d-=g);c.changedTouches&&(j=c.changedTouches[0].pageX);return Math.max(0,Math.min(1,(j-e)/d))}t.Ea=function(){u.d(document,"keyup",u.bind(this,this.Y))};t.Y=function(a){37==a.which?(a.preventDefault(),this.mc()):39==a.which&&(a.preventDefault(),this.nc())};t.Da=function(){u.t(document,"keyup",u.bind(this,this.Y))};u.va=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});
function C(a,c){a.V(c);c.d("click",u.bind(a,function(){this.Na()}))}u.va.prototype.e=function(){return u.c.prototype.e.call(this,"ul",{className:"vjs-menu"})};u.G=u.n.extend({f:function(a,c){u.n.call(this,a,c);c.selected?(this.q("vjs-selected"),this.b.setAttribute("aria-selected",f)):this.b.setAttribute("aria-selected",l)}});u.G.prototype.e=function(a,c){return u.n.prototype.e.call(this,"li",u.i.B({className:"vjs-menu-item",innerHTML:this.g.label},c))};u.G.prototype.r=function(){this.selected(f)};
u.G.prototype.selected=function(a){a?(this.q("vjs-selected"),this.b.setAttribute("aria-selected",f)):(this.v("vjs-selected"),this.b.setAttribute("aria-selected",l))};
u.ba=u.c.extend({f:function(a,c,d){this.L=a;c=u.i.B(ca(a),c);this.s={};this.ic=c.poster;this.Ub=c.controls;u.c.call(this,this,c,d);this.O("play",function(a){u.j(this.b,{type:"firstplay",target:this.b})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Pc);this.d("play",this.xb);this.d("firstplay",this.Qc);this.d("pause",this.wb);this.d("progress",this.Sc);this.d("durationchange",this.Oc);this.d("error",this.tb);this.d("fullscreenchange",this.Rc);u.Ga[this.J]=
this;c.plugins&&u.i.ka(c.plugins,function(a,c){this[a](c)},this)}});t=u.ba.prototype;t.g=u.options;t.C=function(){u.Ga[this.J]=h;this.L&&this.L.player&&(this.L.player=h);this.b&&this.b.player&&(this.b.player=h);clearInterval(this.Ia);this.oa();this.h&&this.h.C();u.c.prototype.C.call(this)};
function ca(a){var c={sources:[],tracks:[]};u.i.B(c,u.kb(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,j=e.length;g<j;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?c.sources.push(u.kb(a)):"track"===d&&c.tracks.push(u.kb(a));return c}
t.e=function(){var a=this.b=u.c.prototype.e.call(this,"div"),c=this.L;c.removeAttribute("controls");c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes())for(var d=c.childNodes.length,e=0,g=c.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&c.removeChild(g[0]);c.id=c.id||"vjs_video_"+u.u++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.q("vjs-paused");this.width(this.g.width,
f);this.height(this.g.height,f);c.parentNode&&c.parentNode.insertBefore(a,c);u.mb(c,a);return a};
function D(a,c,d){a.h?E(a):"Html5"!==c&&a.L&&(a.b.removeChild(a.L),a.L.gc=h,a.L=h);a.Z=c;a.X=l;var e=u.i.B({source:d,parentEl:a.b},a.g[c.toLowerCase()]);d&&(d.src==a.s.src&&0<a.s.currentTime&&(e.startTime=a.s.currentTime),a.s.src=d.src);a.h=new window.videojs[c](a,e);a.h.K(function(){this.a.Ma();if(!this.m.jc){var a=this.a;a.rb=f;a.Ia=setInterval(u.bind(a,function(){this.s.bb<this.buffered().end(0)?this.j("progress"):1==F(this)&&(clearInterval(this.Ia),this.j("progress"))}),500);a.h.O("progress",
function(){this.m.jc=f;var a=this.a;a.rb=l;clearInterval(a.Ia)})}this.m.oc||(a=this.a,a.sb=f,a.d("play",a.pc),a.d("pause",a.oa),a.h.O("timeupdate",function(){this.m.oc=f;G(this.a)}))})}function E(a){a.X=l;a.h.C();a.rb&&(a.rb=l,clearInterval(a.Ia));a.sb&&G(a);a.h=l}function G(a){a.sb=l;a.oa();a.t("play",a.pc);a.t("pause",a.oa)}t.pc=function(){this.Wb&&this.oa();this.Wb=setInterval(u.bind(this,function(){this.j("timeupdate")}),250)};t.oa=function(){clearInterval(this.Wb)};
t.Pc=function(){this.g.loop&&(this.currentTime(0),this.play())};t.xb=function(){u.v(this.b,"vjs-paused");u.q(this.b,"vjs-playing")};t.Qc=function(){this.g.starttime&&this.currentTime(this.g.starttime)};t.wb=function(){u.v(this.b,"vjs-playing");u.q(this.b,"vjs-paused")};t.Sc=function(){1==F(this)&&this.j("loadedalldata")};t.Oc=function(){this.duration(H(this,"duration"))};t.tb=function(a){u.log("Video Error",a)};t.Rc=function(){this.N?this.q("vjs-fullscreen"):this.v("vjs-fullscreen")};
function I(a,c,d){if(a.h&&a.h.X)a.h.K(function(){this[c](d)});else try{a.h[c](d)}catch(e){u.log(e)}}function H(a,c){if(a.h.X)try{return a.h[c]()}catch(d){if(a.h[c]===b)u.log("Video.js: "+c+" method not defined for "+a.Z+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+c+" unavailable on "+a.Z+" playback technology element.",d),a.h.X=l,d;u.log(d)}}}t.play=function(){I(this,"play");return this};t.pause=function(){I(this,"pause");return this};
t.paused=function(){return H(this,"paused")===l?l:f};t.currentTime=function(a){return a!==b?(this.s.qd=a,I(this,"setCurrentTime",a),this.sb&&this.j("timeupdate"),this):this.s.currentTime=H(this,"currentTime")||0};t.duration=function(a){return a!==b?(this.s.duration=parseFloat(a),this):this.s.duration};t.buffered=function(){var a=H(this,"buffered"),c=this.s.bb=this.s.bb||0;a&&(0<a.length&&a.end(0)!==c)&&(c=a.end(0),this.s.bb=c);return u.hb(0,c)};
function F(a){return a.duration()?a.buffered().end(0)/a.duration():0}t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.s.volume=a,I(this,"setVolume",a),u.Zc(a),this;a=parseFloat(H(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(I(this,"setMuted",a),this):H(this,"muted")||l};t.La=function(){return H(this,"supportsFullScreen")||l};
t.Ka=function(){var a=u.Ab.Ka;this.N=f;a?(u.d(document,a.da,u.bind(this,function(){this.N=document[a.N];this.N===l&&u.t(document,a.da,arguments.callee);this.j("fullscreenchange")})),this.h.m.$b===l&&this.g.flash.iFrameMode!==f&&(this.pause(),E(this),u.d(document,a.da,u.bind(this,function(){u.t(document,a.da,arguments.callee);D(this,this.Z,{src:this.s.src})}))),this.b[a.Vc]()):this.h.La()?(this.j("fullscreenchange"),I(this,"enterFullScreen")):(this.j("fullscreenchange"),this.Kc=f,this.Fc=document.documentElement.style.overflow,
u.d(document,"keydown",u.bind(this,this.Zb)),document.documentElement.style.overflow="hidden",u.q(document.body,"vjs-full-window"),u.q(this.b,"vjs-fullscreen"),this.j("enterFullWindow"));return this};function J(a){var c=u.Ab.Ka;a.N=l;c?(a.h.m.$b===l&&a.g.flash.iFrameMode!==f&&(a.pause(),E(a),u.d(document,c.da,u.bind(a,function(){u.t(document,c.da,arguments.callee);D(this,this.Z,{src:this.s.src})}))),document[c.Cc]()):(a.h.La()?I(a,"exitFullScreen"):K(a),a.j("fullscreenchange"))}
t.Zb=function(a){27===a.keyCode&&(this.N===f?J(this):K(this))};function K(a){a.Kc=l;u.t(document,"keydown",a.Zb);document.documentElement.style.overflow=a.Fc;u.v(document.body,"vjs-full-window");u.v(a.b,"vjs-fullscreen");a.j("exitFullWindow")}
t.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.g.techOrder;d<e.length;d++){var g=u.W(e[d]),j=window.videojs[g];if(j.isSupported())for(var k=0,q=c;k<q.length;k++){var n=q[k];if(j.canPlaySource(n)){c={source:n,h:g};break a}}}c=l}c?(a=c.source,c=c.h,c==this.Z?this.src(a):D(this,c,a)):this.b.appendChild(u.e("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.Z].canPlaySource(a)?this.src(a.src):this.src([a]):(this.s.src=a,this.X?(I(this,"src",a),"auto"==this.g.preload&&this.load(),this.g.autoplay&&this.play()):this.K(function(){this.src(a)}));return this};t.load=function(){I(this,"load");return this};t.currentSrc=function(){return H(this,"currentSrc")||this.s.src||""};t.Ha=function(a){return a!==b?(I(this,"setPreload",a),this.g.preload=a,this):H(this,"preload")};
t.autoplay=function(a){return a!==b?(I(this,"setAutoplay",a),this.g.autoplay=a,this):H(this,"autoplay")};t.loop=function(a){return a!==b?(I(this,"setLoop",a),this.g.loop=a,this):H(this,"loop")};t.poster=function(a){a!==b&&(this.ic=a);return this.ic};t.controls=function(a){a!==b&&(this.Ub=a);return this.Ub};t.error=function(){return H(this,"error")};var L,M,N,O;
if(document.md!==b)L="requestFullscreen",M="exitFullscreen",N="fullscreenchange",O="fullScreen";else for(var P=["moz","webkit"],Q=P.length-1;0<=Q;Q--){var R=P[Q];if(("moz"!=R||document.mozFullScreenEnabled)&&document[R+"CancelFullScreen"]!==b)L=R+"RequestFullScreen",M=R+"CancelFullScreen",N=R+"fullscreenchange",O="webkit"==R?R+"IsFullScreen":R+"FullScreen"}L&&(u.Ab.Ka={Vc:L,Cc:M,da:N,N:O});
u.aa=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.O("play",u.bind(this,function(){var a,c=u.bind(this,this.ma),g=u.bind(this,this.za);this.ma();"ontouchstart"in window||(this.a.d("mouseover",c),this.a.d("mouseout",g),this.a.d("pause",u.bind(this,this.fc)),this.a.d("play",u.bind(this,this.Na)));a=l;this.a.d("touchstart",function(){a=f});this.a.d("touchmove",function(){a=l});this.a.d("touchend",u.bind(this,function(c){var e;a&&(e=this.o().className.search("fade-in"),-1!==e?this.za():this.ma());
a=l;this.a.paused()||c.preventDefault()}))}))}});u.aa.prototype.g={rd:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.aa.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.aa.prototype.ma=function(){this.a.options().controls&&u.c.prototype.ma.call(this);this.a.j("controlsvisible")};
u.aa.prototype.za=function(){this.a.options().controls&&u.c.prototype.za.call(this);this.a.j("controlshidden")};u.Ib=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("play",u.bind(this,this.xb));a.d("pause",u.bind(this,this.wb))}});t=u.Ib.prototype;t.ia="Play";t.M=function(){return"vjs-play-control "+u.n.prototype.M.call(this)};t.r=function(){this.a.paused()?this.a.play():this.a.pause()};
t.xb=function(){u.v(this.b,"vjs-paused");u.q(this.b,"vjs-playing");this.b.children[0].children[0].innerHTML="Pause"};t.wb=function(){u.v(this.b,"vjs-playing");u.q(this.b,"vjs-paused");this.b.children[0].children[0].innerHTML="Play"};u.ua=u.n.extend({f:function(a,c){u.n.call(this,a,c)}});u.ua.prototype.ia="Fullscreen";u.ua.prototype.M=function(){return"vjs-fullscreen-control "+u.n.prototype.M.call(this)};
u.ua.prototype.r=function(){this.a.N?(J(this.a),this.b.children[0].children[0].innerHTML="Fullscreen"):(this.a.Ka(),this.b.children[0].children[0].innerHTML="Non-Fullscreen")};u.Ra=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.ra))}});
u.Ra.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Ra.prototype.ra=function(){var a=this.a.zb?this.a.s.currentTime:this.a.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.Aa(a,this.a.duration())};u.Sa=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.ra))}});
u.Sa.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};u.Sa.prototype.ra=function(){this.a.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.Aa(this.a.duration()))};
u.Nb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Nb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.Ya=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.ra))}});
u.Ya.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Ya.prototype.ra=function(){this.a.duration()&&this.a.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.Aa(this.a.duration()-this.a.currentTime()))};u.Xa=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Xa.prototype.g={children:{seekBar:{}}};u.Xa.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};
u.Jb=u.H.extend({f:function(a,c){u.H.call(this,a,c);a.d("timeupdate",u.bind(this,this.qa));a.K(u.bind(this,this.qa))}});t=u.Jb.prototype;t.g={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.hc="timeupdate";t.e=function(){return u.H.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
t.qa=function(){var a=this.a.zb?this.a.s.currentTime:this.a.currentTime();this.b.setAttribute("aria-valuenow",u.round(100*this.lb(),2));this.b.setAttribute("aria-valuetext",u.Aa(a,this.a.duration()))};t.lb=function(){return this.a.currentTime()/this.a.duration()};t.Fa=function(a){u.H.prototype.Fa.call(this,a);this.a.zb=f;this.fd=!this.a.paused();this.a.pause()};t.ub=function(a){a=B(this,a)*this.a.duration();a==this.a.duration()&&(a-=0.1);this.a.currentTime(a)};
t.vb=function(a){u.H.prototype.vb.call(this,a);this.a.zb=l;this.fd&&this.a.play()};t.nc=function(){this.a.currentTime(this.a.currentTime()+5)};t.mc=function(){this.a.currentTime(this.a.currentTime()-5)};u.Ua=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("progress",u.bind(this,this.update))}});u.Ua.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
u.Ua.prototype.update=function(){this.b.style&&(this.b.style.width=u.round(100*F(this.a),2)+"%")};u.Hb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Hb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.Kb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Kb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};
u.$a=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.h&&(a.h.m&&a.h.m.sa===l)&&this.q("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.m&&a.h.m.sa===l?this.q("vjs-hidden"):this.v("vjs-hidden")}))}});u.$a.prototype.g={children:{volumeBar:{}}};u.$a.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};
u.Ob=u.H.extend({f:function(a,c){u.H.call(this,a,c);a.d("volumechange",u.bind(this,this.qa));a.K(u.bind(this,this.qa));setTimeout(u.bind(this,this.update),0)}});t=u.Ob.prototype;t.qa=function(){this.b.setAttribute("aria-valuenow",u.round(100*this.a.volume(),2));this.b.setAttribute("aria-valuetext",u.round(100*this.a.volume(),2)+"%")};t.g={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.hc="volumechange";
t.e=function(){return u.H.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.ub=function(a){this.a.volume(B(this,a))};t.lb=function(){return this.a.volume()};t.nc=function(){this.a.volume(this.a.volume()+0.1)};t.mc=function(){this.a.volume(this.a.volume()-0.1)};u.Qb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Qb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};
u.Pb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Pb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};u.wa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.h&&(a.h.m&&a.h.m.sa===l)&&this.q("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.m&&a.h.m.sa===l?this.q("vjs-hidden"):this.v("vjs-hidden")}))}});
u.wa.prototype.e=function(){return u.n.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.wa.prototype.r=function(){this.a.muted(this.a.muted()?l:f)};
u.wa.prototype.update=function(){var a=this.a.volume(),c=3;0===a||this.a.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.a.muted()?"Unmute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.v(this.b,"vjs-vol-"+a);u.q(this.b,"vjs-vol-"+c)};u.Wa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.poster()||this.A();a.d("play",u.bind(this,this.A))}});
u.Wa.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1}),c=this.a.poster();c&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+c+'")':a.appendChild(u.e("img",{src:c})));return a};u.Wa.prototype.r=function(){this.a.play()};
u.Gb=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("canplay",u.bind(this,this.A));a.d("canplaythrough",u.bind(this,this.A));a.d("playing",u.bind(this,this.A));a.d("seeked",u.bind(this,this.A));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.A));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}});
u.Gb.prototype.e=function(){var a,c;"string"==typeof this.a.o().style.WebkitBorderRadius||"string"==typeof this.a.o().style.MozBorderRadius||"string"==typeof this.a.o().style.kd||"string"==typeof this.a.o().style.ld?(a="vjs-loading-spinner",c='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",c="");return u.c.prototype.e.call(this,
"div",{className:a,innerHTML:c})};u.Pa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("play",u.bind(this,this.A))}});u.Pa.prototype.e=function(){return u.n.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};u.Pa.prototype.r=function(){this.a.play()};u.p=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d)}});u.p.prototype.r=function(){this.a.paused()?this.a.play():this.a.pause()};
u.p.prototype.m={volumeControl:f,fullscreenResize:l,progressEvents:l,timeupdateEvents:l};u.media={};u.media.Oa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function da(){var a=u.media.Oa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Oa.length-1;0<=i;i--)u.p.prototype[u.media.Oa[i]]=da();
u.l=u.p.extend({f:function(a,c,d){this.m.sa=u.l.Bc();this.m.Mc=!u.tc;u.p.call(this,a,c,d);(c=c.source)&&this.b.currentSrc==c.src?a.j("loadstart"):c&&(this.b.src=c.src);a.K(function(){this.g.autoplay&&this.paused()&&(this.L.poster=h,this.play())});this.d("click",this.r);for(a=u.l.Ta.length-1;0<=a;a--)u.d(this.b,u.l.Ta[a],u.bind(this.a,this.Hc));this.Ma()}});t=u.l.prototype;t.C=function(){u.p.prototype.C.call(this)};
t.e=function(){var a=this.a,c=a.L;if(!c||this.m.Mc===l)c?(a.o().removeChild(c),c=c.cloneNode(l)):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.mb(c,a.o());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.g[g]!==h&&(c[g]=a.g[g])}return c};t.Hc=function(a){this.j(a);a.stopPropagation()};t.play=function(){this.b.play()};t.pause=function(){this.b.pause()};t.paused=function(){return this.b.paused};t.currentTime=function(){return this.b.currentTime};
t.Yc=function(a){try{this.b.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.b.duration||0};t.buffered=function(){return this.b.buffered};t.volume=function(){return this.b.volume};t.cd=function(a){this.b.volume=a};t.muted=function(){return this.b.muted};t.ad=function(a){this.b.muted=a};t.width=function(){return this.b.offsetWidth};t.height=function(){return this.b.offsetHeight};
t.La=function(){return"function"==typeof this.b.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:l};t.src=function(a){this.b.src=a};t.load=function(){this.b.load()};t.currentSrc=function(){return this.b.currentSrc};t.Ha=function(){return this.b.Ha};t.bd=function(a){this.b.Ha=a};t.autoplay=function(){return this.b.autoplay};t.Xc=function(a){this.b.autoplay=a};t.loop=function(){return this.b.loop};t.$c=function(a){this.b.loop=a};t.error=function(){return this.b.error};
u.l.isSupported=function(){return!!document.createElement("video").canPlayType};u.l.cb=function(a){return!!document.createElement("video").canPlayType(a.type)};u.l.Bc=function(){var a=u.Za.volume;u.Za.volume=a/2+0.1;return a!==u.Za.volume};u.l.Ta="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.rc&&3>u.qc&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
u.k=u.p.extend({f:function(a,c,d){u.p.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.b=u.e("div",{id:a.id()+"_temp_flash"}),j=a.id()+"_flash_api";a=a.g;var k=u.i.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Ha,loop:a.loop,muted:a.muted},c.flashVars),q=u.i.B({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.i.B({id:j,name:j,"class":"vjs-tech"},c.attributes);d&&(k.src=encodeURIComponent(u.ac(d.src)));
u.mb(g,e);c.startTime&&this.K(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!u.sc){var s=u.e("iframe",{id:j+"_iframe",name:j+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.d(s,"load",u.bind(this,function(){var a,d=s.contentWindow;a=s.contentDocument?s.contentDocument:s.contentWindow.document;a.write(u.k.bc(c.swf,k,q,n));d.player=
this.a;d.ready=u.bind(this.a,function(c){c=a.getElementById(c);var d=this.h;d.b=c;u.d(c,"click",d.bind(d.r));u.k.eb(d)});d.events=u.bind(this.a,function(a,c){this&&"flash"===this.Z&&this.j(c)});d.errors=u.bind(this.a,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(s,g)}else u.k.Gc(c.swf,g,k,q,n)}});t=u.k.prototype;t.C=function(){u.p.prototype.C.call(this)};t.play=function(){this.b.vjs_play()};t.pause=function(){this.b.vjs_pause()};
t.src=function(a){a=u.ac(a);this.b.vjs_src(a);if(this.a.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.load=function(){this.b.vjs_load()};t.poster=function(){this.b.vjs_getProperty("poster")};t.buffered=function(){return u.hb(0,this.b.vjs_getProperty("buffered"))};t.La=r(l);var S=u.k.prototype,T="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),U="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function ea(){var a=T[V],c=a.charAt(0).toUpperCase()+a.slice(1);S["set"+c]=function(c){return this.b.vjs_setProperty(a,c)}}function W(a){S[a]=function(){return this.b.vjs_getProperty(a)}}var V;for(V=0;V<T.length;V++)W(T[V]),ea();for(V=0;V<U.length;V++)W(U[V]);u.k.isSupported=function(){return 10<=u.k.version()[0]};u.k.cb=function(a){if(a.type in u.k.Jc)return"maybe"};u.k.Jc={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
u.k.onReady=function(a){a=u.o(a);var c=a.player||a.parentNode.player,d=c.h;a.player=c;d.b=a;d.d("click",d.r);u.k.eb(d)};u.k.eb=function(a){a.o().vjs_getProperty?a.Ma():setTimeout(function(){u.k.eb(a)},50)};u.k.onEvent=function(a,c){u.o(a).player.j(c)};u.k.onError=function(a,c){u.o(a).player.j("error");u.log("Flash Error",c,a)};
u.k.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.k.Gc=function(a,c,d,e,g){a=u.k.bc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var j=d.childNodes[0];setTimeout(function(){j.style.display="block"},1E3)};
u.k.bc=function(a,c,d,e){var g="",j="",k="";c&&u.i.ka(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.i.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.i.ka(d,function(a,c){j+='<param name="'+a+'" value="'+c+'" />'});e=u.i.B({data:a,width:"100%",height:"100%"},e);u.i.ka(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+j+"</object>"};
u.xc=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d);if(!a.g.sources||0===a.g.sources.length){c=0;for(d=a.g.techOrder;c<d.length;c++){var e=u.W(d[c]),g=window.videojs[e];if(g&&g.isSupported()){D(a,e);break}}}else a.src(a.g.sources)}});function X(a){a.pa=a.pa||[];return a.pa}function fa(a,c,d){for(var e=a.pa,g=0,j=e.length,k,q;g<j;g++)k=e[g],k.id()===c?(k.show(),q=k):d&&(k.F()==d&&0<k.mode())&&k.disable();(c=q?q.F():d?d:l)&&a.j(c+"trackchange")}
u.R=u.c.extend({f:function(a,c){u.c.call(this,a,c);this.J=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.u++;this.lc=c.src;this.Dc=c["default"]||c.dflt;this.sd=c.title;this.pd=c.srclang;this.Lc=c.label;this.ca=[];this.Rb=[];this.ea=this.fa=0;this.a.d("fullscreenchange",u.bind(this,this.yc))}});t=u.R.prototype;t.F=p("z");t.src=p("lc");t.ib=p("Dc");t.label=p("Lc");t.readyState=p("fa");t.mode=p("ea");t.yc=function(){this.b.style.fontSize=this.a.N?140*(screen.width/this.a.width())+"%":""};
t.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-"+this.z+" vjs-text-track"})};t.show=function(){ga(this);this.ea=2;u.c.prototype.show.call(this)};t.A=function(){ga(this);this.ea=1;u.c.prototype.A.call(this)};t.disable=function(){2==this.ea&&this.A();this.a.t("timeupdate",u.bind(this,this.update,this.J));this.a.t("ended",u.bind(this,this.reset,this.J));this.reset();this.a.P.textTrackDisplay.removeChild(this);this.ea=0};
function ga(a){0===a.fa&&a.load();0===a.ea&&(a.a.d("timeupdate",u.bind(a,a.update,a.J)),a.a.d("ended",u.bind(a,a.reset,a.J)),("captions"===a.z||"subtitles"===a.z)&&a.a.P.textTrackDisplay.V(a))}t.load=function(){0===this.fa&&(this.fa=1,u.get(this.lc,u.bind(this,this.Tc),u.bind(this,this.tb)))};t.tb=function(a){this.error=a;this.fa=3;this.j("error")};
t.Tc=function(a){var c,d;a=a.split("\n");for(var e="",g=1,j=a.length;g<j;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.ca.length;c={id:c,index:this.ca.length};d=e.split(" --\x3e ");c.startTime=ha(d[0]);c.la=ha(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.ca.push(c)}this.fa=2;this.j("loaded")};
function ha(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.ca.length){var a=this.a.currentTime();if(this.yb===b||a<this.yb||this.Ca<=a){var c=this.ca,d=this.a.duration(),e=0,g=l,j=[],k,q,n,s;a>=this.Ca||this.Ca===b?s=this.jb!==b?this.jb:0:(g=f,s=this.qb!==b?this.qb:c.length-1);for(;;){n=c[s];if(n.la<=a)e=Math.max(e,n.la),n.ya&&(n.ya=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.ya&&(n.ya=l),!g)break}else g?(j.splice(0,0,n),q===b&&(q=s),k=s):(j.push(n),k===b&&(k=s),q=s),d=Math.min(d,n.la),e=Math.max(e,n.startTime),
n.ya=f;if(g)if(0===s)break;else s--;else if(s===c.length-1)break;else s++}this.Rb=j;this.Ca=d;this.yb=e;this.jb=k;this.qb=q;a=this.Rb;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.b.innerHTML=c;this.j("cuechange")}}};t.reset=function(){this.Ca=0;this.yb=this.a.duration();this.qb=this.jb=0};u.Db=u.R.extend();u.Db.prototype.z="captions";u.Lb=u.R.extend();u.Lb.prototype.z="subtitles";u.Fb=u.R.extend();u.Fb.prototype.z="chapters";
u.Mb=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d);if(a.g.tracks&&0<a.g.tracks.length){c=this.a;a=a.g.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=c,j=e.kind,k=e.label,q=e.language,n=e;e=g.pa=g.pa||[];n=n||{};n.kind=j;n.label=k;n.language=q;j=u.W(j||"subtitles");g=new window.videojs[j+"Track"](g,n);e.push(g)}}}});u.Mb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};
u.T=u.G.extend({f:function(a,c){var d=this.$=c.track;c.label=d.label();c.selected=d.ib();u.G.call(this,a,c);this.a.d(d.F()+"trackchange",u.bind(this,this.update))}});u.T.prototype.r=function(){u.G.prototype.r.call(this);fa(this.a,this.$.J,this.$.F())};u.T.prototype.update=function(){2==this.$.mode()?this.selected(f):this.selected(l)};u.Va=u.T.extend({f:function(a,c){c.track={F:function(){return c.kind},gc:a,label:r("Off"),ib:r(l),mode:r(l)};u.T.call(this,a,c);this.selected(f)}});
u.Va.prototype.r=function(){u.T.prototype.r(this);fa(this.a,this.$.J,this.$.F())};u.Va.prototype.update=function(){for(var a=X(this.a),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.F()==this.$.F()&&2==e.mode()&&(g=l);g?this.selected(f):this.selected(l)};u.S=u.n.extend({f:function(a,c){u.n.call(this,a,c);this.Ba=this.gb();0===this.na.length&&this.A();this.d("keyup",this.Y);this.b.setAttribute("aria-haspopup",f);this.b.setAttribute("role","button")}});t=u.S.prototype;t.ha=l;
t.gb=function(){var a=new u.va(this.a);a.o().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.W(this.z),dd:-1}));C(a,new u.Va(this.a,{kind:this.z}));this.na=this.Vb();for(var c=0;c<this.na.length;c++)C(a,this.na[c]);this.V(a);return a};t.Vb=function(){for(var a=[],c,d=0;d<X(this.a).length;d++)c=X(this.a)[d],c.F()===this.z&&a.push(new u.T(this.a,{track:c}));return a};t.M=function(){return this.className+" vjs-menu-button "+u.n.prototype.M.call(this)};t.Ea=m();t.Da=m();
t.r=function(){this.O("mouseout",u.bind(this,function(){this.Ba.Na();this.b.blur()}));this.ha?Y(this):ia(this)};t.Y=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.ha?Y(this):ia(this);27==a.which&&(a.preventDefault(),this.ha&&Y(this))};function ia(a){a.ha=f;a.Ba.fc();a.b.setAttribute("aria-pressed",f);a.b.children[1].children[0].focus()}function Y(a){a.ha=l;a.Ba.Na();a.b.setAttribute("aria-pressed",l)}
u.ta=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.b.setAttribute("aria-label","Captions Menu")}});u.ta.prototype.z="captions";u.ta.prototype.ia="Captions";u.ta.prototype.className="vjs-captions-button";u.xa=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.b.setAttribute("aria-label","Subtitles Menu")}});u.xa.prototype.z="subtitles";u.xa.prototype.ia="Subtitles";u.xa.prototype.className="vjs-subtitles-button";
u.Eb=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.b.setAttribute("aria-label","Chapters Menu")}});t=u.Eb.prototype;t.z="chapters";t.ia="Chapters";t.className="vjs-chapters-button";t.Vb=function(){for(var a=[],c,d=0;d<X(this.a).length;d++)c=X(this.a)[d],c.F()===this.z&&a.push(new u.T(this.a,{track:c}));return a};
t.gb=function(){for(var a=X(this.a),c=0,d=a.length,e,g,j=this.na=[];c<d;c++)if(e=a[c],e.F()==this.z&&e.ib()){if(2>e.readyState()){this.nd=e;e.d("loaded",u.bind(this,this.gb));return}g=e;break}a=this.Ba=new u.va(this.a);a.b.appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.W(this.z),dd:-1}));if(g){e=g.ca;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new u.Qa(this.a,{track:g,cue:k}),j.push(k),a.V(k)}this.V(a);0<this.na.length&&this.show();return a};
u.Qa=u.G.extend({f:function(a,c){var d=this.$=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.la;u.G.call(this,a,c);d.d("cuechange",u.bind(this,this.update))}});u.Qa.prototype.r=function(){u.G.prototype.r.call(this);this.a.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.Qa.prototype.update=function(){var a=this.cue,c=this.a.currentTime();a.startTime<=c&&c<a.la?this.selected(f):this.selected(l)};
u.i.B(u.aa.prototype.g.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var k,q,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(q=d(n,k),q!==b?n[k]=q:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.Sb=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),v(c,a)));else{u.ab();break}else u.gd||u.ab()};u.ab=function(){setTimeout(u.Sb,1)};u.O(window,"load",function(){u.gd=f});u.ab();u.Uc=function(a,c){u.ba.prototype[a]=c};var ja=this;ja.hd=f;function $(a,c){var d=a.split("."),e=ja;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.cache",u.ja);$("videojs.Component",u.c);u.c.prototype.dispose=u.c.prototype.C;u.c.prototype.createEl=u.c.prototype.e;u.c.prototype.el=u.c.prototype.o;u.c.prototype.addChild=u.c.prototype.V;u.c.prototype.children=u.c.prototype.children;u.c.prototype.on=u.c.prototype.d;u.c.prototype.off=u.c.prototype.t;u.c.prototype.one=u.c.prototype.O;u.c.prototype.trigger=u.c.prototype.j;u.c.prototype.triggerReady=u.c.prototype.Ma;
u.c.prototype.show=u.c.prototype.show;u.c.prototype.hide=u.c.prototype.A;u.c.prototype.width=u.c.prototype.width;u.c.prototype.height=u.c.prototype.height;u.c.prototype.dimensions=u.c.prototype.Ec;u.c.prototype.ready=u.c.prototype.K;$("videojs.Player",u.ba);u.ba.prototype.dispose=u.ba.prototype.C;$("videojs.MediaLoader",u.xc);$("videojs.TextTrackDisplay",u.Mb);$("videojs.ControlBar",u.aa);$("videojs.Button",u.n);$("videojs.PlayToggle",u.Ib);$("videojs.FullscreenToggle",u.ua);
$("videojs.BigPlayButton",u.Pa);$("videojs.LoadingSpinner",u.Gb);$("videojs.CurrentTimeDisplay",u.Ra);$("videojs.DurationDisplay",u.Sa);$("videojs.TimeDivider",u.Nb);$("videojs.RemainingTimeDisplay",u.Ya);$("videojs.Slider",u.H);$("videojs.ProgressControl",u.Xa);$("videojs.SeekBar",u.Jb);$("videojs.LoadProgressBar",u.Ua);$("videojs.PlayProgressBar",u.Hb);$("videojs.SeekHandle",u.Kb);$("videojs.VolumeControl",u.$a);$("videojs.VolumeBar",u.Ob);$("videojs.VolumeLevel",u.Qb);
$("videojs.VolumeHandle",u.Pb);$("videojs.MuteToggle",u.wa);$("videojs.PosterImage",u.Wa);$("videojs.Menu",u.va);$("videojs.MenuItem",u.G);$("videojs.SubtitlesButton",u.xa);$("videojs.CaptionsButton",u.ta);$("videojs.ChaptersButton",u.Eb);$("videojs.MediaTechController",u.p);u.p.prototype.features=u.p.prototype.m;u.p.prototype.m.volumeControl=u.p.prototype.m.sa;u.p.prototype.m.fullscreenResize=u.p.prototype.m.$b;u.p.prototype.m.progressEvents=u.p.prototype.m.jc;u.p.prototype.m.timeupdateEvents=u.p.prototype.m.oc;
$("videojs.Html5",u.l);u.l.Events=u.l.Ta;u.l.isSupported=u.l.isSupported;u.l.canPlaySource=u.l.cb;u.l.prototype.setCurrentTime=u.l.prototype.Yc;u.l.prototype.setVolume=u.l.prototype.cd;u.l.prototype.setMuted=u.l.prototype.ad;u.l.prototype.setPreload=u.l.prototype.bd;u.l.prototype.setAutoplay=u.l.prototype.Xc;u.l.prototype.setLoop=u.l.prototype.$c;$("videojs.Flash",u.k);u.k.isSupported=u.k.isSupported;u.k.canPlaySource=u.k.cb;u.k.onReady=u.k.onReady;$("videojs.TextTrack",u.R);u.R.prototype.label=u.R.prototype.label;
$("videojs.CaptionsTrack",u.Db);$("videojs.SubtitlesTrack",u.Lb);$("videojs.ChaptersTrack",u.Fb);$("videojs.autoSetup",u.Sb);$("videojs.plugin",u.Uc);$("videojs.createTimeRange",u.hb);})();//@ sourceMappingURL=video.js.map
