var b=void 0,f=!0,h=null,k=!1;function l(){return function(){}}function p(a){return function(){return this[a]}}function r(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.Ga[a])return u.Ga[a];a=u.o(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.ba(a,c,d)}var v=u;u.Fb="GENERATED_CDN_VSN";
u.Eb="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{swf:u.Eb+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.Ga={};"GENERATED_CDN_VSN"!=u.Fb&&(v.options.flash.swf=u.Eb+"vjs.zencdn.net/"+u.Fb+"/video-js.swf");u.ha=u.CoreObject=l();
u.ha.extend=function(a){var c,d;a=a||{};c=a.f||this.prototype.f||l();d=function(){c.apply(this,arguments)};d.prototype=u.i.create(this.prototype);d.prototype.constructor=d;d.extend=u.ha.extend;d.create=u.ha.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.ha.create=function(){var a=u.i.create(this.prototype);this.apply(a,arguments);return a};
u.d=function(a,c,d){var e=u.getData(a);e.v||(e.v={});e.v[c]||(e.v[c]=[]);d.u||(d.u=u.u++);e.v[c].push(d);e.Q||(e.disabled=k,e.Q=function(c){if(!e.disabled){c=u.ac(c);var d=e.v[c.type];if(d)for(var d=d.slice(0),j=0,q=d.length;j<q&&!c.fc();j++)d[j].call(a,c)}});1==e.v[c].length&&(document.addEventListener?a.addEventListener(c,e.Q,k):document.attachEvent&&a.attachEvent("on"+c,e.Q))};
u.t=function(a,c,d){if(u.ec(a)){var e=u.getData(a);if(e.v)if(c){var g=e.v[c];if(g){if(d){if(d.u)for(e=0;e<g.length;e++)g[e].u===d.u&&g.splice(e--,1)}else e.v[c]=[];u.Wb(a,c)}}else for(g in e.v)c=g,e.v[c]=[],u.Wb(a,c)}};u.Wb=function(a,c){var d=u.getData(a);0===d.v[c].length&&(delete d.v[c],document.removeEventListener?a.removeEventListener(c,d.Q,k):document.detachEvent&&a.detachEvent("on"+c,d.Q));u.pb(d.v)&&(delete d.v,delete d.Q,delete d.disabled);u.pb(d)&&u.kc(a)};
u.ac=function(a){function c(){return f}function d(){return k}if(!a||!a.qb){a=u.i.copy(a||window.event);a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=k;a.ob=c};a.ob=d;a.stopPropagation=function(){a.cancelBubble=f;a.qb=c};a.qb=d;a.stopImmediatePropagation=function(){a.fc=c;a.stopPropagation()};a.fc=d;if(a.clientX!=h){var e=document.documentElement,g=document.body;a.pageX=a.clientX+(e&&e.scrollLeft||
g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0);a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.j=function(a,c){var d=u.ec(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.ac(c);d.Q&&d.Q.call(a,c);if(e&&!c.qb())u.j(e,c);else if(!e&&!c.ob()&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=k}return!c.ob()};u.N=function(a,c,d){u.d(a,c,function(){u.t(a,c,arguments.callee);d.apply(this,arguments)})};var w=Object.prototype.hasOwnProperty;
u.e=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)w.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.W=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.i={};u.i.create=Object.create||function(a){function c(){}c.prototype=a;return new c};u.i.la=function(a,c,d){for(var e in a)w.call(a,e)&&c.call(d||this,e,a[e])};u.i.B=function(a,c){if(!c)return a;for(var d in c)w.call(c,d)&&(a[d]=c[d]);return a};
u.i.$b=function(a,c){var d,e,g;a=u.i.copy(a);for(d in c)w.call(c,d)&&(e=a[d],g=c[d],a[d]=u.i.gc(e)&&u.i.gc(g)?u.i.$b(e,g):c[d]);return a};u.i.copy=function(a){return u.i.B({},a)};u.i.gc=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.u||(c.u=u.u++);e.u=d?d+"_"+c.u:c.u;return e};u.ka={};u.u=1;u.expando="vdata"+(new Date).getTime();
u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.u++,u.ka[c]={});return u.ka[c]};u.ec=function(a){a=a[u.expando];return!(!a||u.pb(u.ka[a]))};u.kc=function(a){var c=a[u.expando];if(c){delete u.ka[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.pb=function(a){for(var c in a)if(a[c]!==h)return k;return f};u.r=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
u.z=function(a,c){if(-1!=a.className.indexOf(c)){var d=a.className.split(" ");d.splice(d.indexOf(c),1);a.className=d.join(" ")}};u.Za=u.e("video");u.U=navigator.userAgent;u.uc=!!u.U.match(/iPhone/i);u.tc=!!u.U.match(/iPad/i);u.vc=!!u.U.match(/iPod/i);u.sc=u.uc||u.tc||u.vc;var aa=u,x;var y=u.U.match(/OS (\d+)_/i);x=y&&y[1]?y[1]:b;aa.jd=x;u.qc=!!u.U.match(/Android.*AppleWebKit/i);var ba=u,z=u.U.match(/Android (\d+)\./i);ba.pc=z&&z[1]?z[1]:h;u.rc=function(){return!!u.U.match("Firefox")};
u.lb=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,m=d.length-1;0<=m;m--){e=d[m].name;g=d[m].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:k;c[e]=g}return c};
u.od=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(c=c.replace(/\-(\w)/g,function(a,c){return c.toUpperCase()}),d=a.currentStyle[c]);return d};u.nb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Cb={};u.o=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.Aa=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),m=Math.floor(c/60%60),j=Math.floor(c/3600),g=0<g||0<j?g+":":"";return g+(((g||10<=m)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.zc=function(){document.body.focus();document.onselectstart=r(k)};u.ed=function(){document.onselectstart=r(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
u.hb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(m){d(m)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(j){d&&d(j)}};u.Zc=function(a){var c=window.localStorage||k;if(c)try{c.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.cc=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Hc="getBoundingClientRect"in document.documentElement?function(a){var c;try{c=a.getBoundingClientRect()}catch(d){}if(!c)return 0;a=document.body;return c.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var c=a.offsetLeft;a=a.offsetParent;)c+=a.offsetLeft;return c};
u.c=u.ha.extend({f:function(a,c,d){this.b=a;this.g=u.i.copy(this.g);c=this.options(c);this.J=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.u++);this.Mc=c.name||h;this.a=c.el||this.e();this.D=[];this.fb={};this.P={};if((a=this.g)&&a.children){var e=this;u.i.la(a.children,function(a,c){c!==k&&!c.loadEvent&&(e[a]=e.V(a,c))})}this.K(d)}});t=u.c.prototype;
t.C=function(){if(this.D)for(var a=this.D.length-1;0<=a;a--)this.D[a].C&&this.D[a].C();this.P=this.fb=this.D=h;this.t();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.kc(this.a);this.a=h};t.Tc=p("b");t.options=function(a){return a===b?this.g:this.g=u.i.$b(this.g,a)};t.e=function(a,c){return u.e(a,c)};t.o=p("a");t.id=p("J");t.name=p("Mc");t.children=p("D");
t.V=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.W(e),c.name=e,d=new window.videojs[d](this.b||this,c)):d=a;this.D.push(d);"function"===typeof d.id&&(this.fb[d.id()]=d);(e=e||d.name&&d.name())&&(this.P[e]=d);"function"===typeof d.el&&d.el()&&this.a.appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.P[a]);if(a&&this.D){for(var c=k,d=this.D.length-1;0<=d;d--)if(this.D[d]===a){c=f;this.D.splice(d,1);break}c&&(this.fb[a.id]=h,this.P[a.name]=h,(c=a.o())&&c.parentNode===this.a&&this.a.removeChild(a.o()))}};t.L=r("");t.d=function(a,c){u.d(this.a,a,u.bind(this,c));return this};t.t=function(a,c){u.t(this.a,a,c);return this};t.N=function(a,c){u.N(this.a,a,u.bind(this,c));return this};t.j=function(a,c){u.j(this.a,a,c);return this};
t.K=function(a){a&&(this.X?a.call(this):(this.Ja===b&&(this.Ja=[]),this.Ja.push(a)));return this};t.Ma=function(){this.X=f;var a=this.Ja;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Ja=[];this.j("ready")}};t.r=function(a){u.r(this.a,a);return this};t.z=function(a){u.z(this.a,a);return this};t.show=function(){this.a.style.display="block";return this};t.A=function(){this.a.style.display="none";return this};t.na=function(){this.z("vjs-fade-out");this.r("vjs-fade-in");return this};
t.za=function(){this.z("vjs-fade-in");this.r("vjs-fade-out");return this};t.hc=function(){var a=this.a.style;a.display="block";a.opacity=1;a.visibility="visible";return this};t.Na=function(){var a=this.a.style;a.display="";a.opacity="";a.visibility="";return this};t.width=function(a,c){return A(this,"width",a,c)};t.height=function(a,c){return A(this,"height",a,c)};t.Dc=function(a,c){return this.width(a,f).height(c)};
function A(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.j("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.W(c)],10)}
u.n=u.c.extend({f:function(a,c){u.c.call(this,a,c);var d=k;this.d("touchstart",function(){d=f});this.d("touchmove",function(){d=k});var e=this;this.d("touchend",function(a){d&&e.q(a);a.preventDefault();a.stopPropagation()});this.d("click",this.q);this.d("focus",this.Ea);this.d("blur",this.Da)}});t=u.n.prototype;
t.e=function(a,c){c=u.i.B({className:this.L(),innerHTML:'<div><span class="vjs-control-text">'+(this.ja||"Need Text")+"</span></div>",Wc:"button","aria-live":"polite",tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.L=function(){return"vjs-control "+u.c.prototype.L.call(this)};t.q=l();t.Ea=function(){u.d(document,"keyup",u.bind(this,this.Y))};t.Y=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.q()};t.Da=function(){u.t(document,"keyup",u.bind(this,this.Y))};
u.H=u.c.extend({f:function(a,c){u.c.call(this,a,c);this.yc=this.P[this.g.barName];this.handle=this.P[this.g.handleName];a.d(this.ic,u.bind(this,this.update));this.d("mousedown",this.Fa);this.d("touchstart",this.Fa);this.d("focus",this.Ea);this.d("blur",this.Da);this.b.d("controlsvisible",u.bind(this,this.update));a.K(u.bind(this,this.update));this.I={}}});t=u.H.prototype;
t.e=function(a,c){c=u.i.B({Wc:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.Fa=function(a){a.preventDefault();u.zc();this.I.move=u.bind(this,this.vb);this.I.end=u.bind(this,this.wb);u.d(document,"mousemove",this.I.move);u.d(document,"mouseup",this.I.end);u.d(document,"touchmove",this.I.move);u.d(document,"touchend",this.I.end);this.vb(a)};
t.wb=function(){u.ed();u.t(document,"mousemove",this.I.move,k);u.t(document,"mouseup",this.I.end,k);u.t(document,"touchmove",this.I.move,k);u.t(document,"touchend",this.I.end,k);this.update()};t.update=function(){if(this.a){var a,c=this.mb(),d=this.handle,e=this.yc;isNaN(c)&&(c=0);a=c;if(d){a=this.a.offsetWidth;var g=d.o().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.o().style.left=u.round(100*c,2)+"%"}e.o().style.width=u.round(100*a,2)+"%"}};
function B(a,c){var d=a.a,e=u.Hc(d),d=d.offsetWidth,g=a.handle,m=c.pageX;g&&(g=g.o().offsetWidth,e+=g/2,d-=g);0===m&&c.changedTouches&&(m=c.changedTouches[0].pageX);return Math.max(0,Math.min(1,(m-e)/d))}t.Ea=function(){u.d(document,"keyup",u.bind(this,this.Y))};t.Y=function(a){37==a.which?(a.preventDefault(),this.mc()):39==a.which&&(a.preventDefault(),this.nc())};t.Da=function(){u.t(document,"keyup",u.bind(this,this.Y))};u.va=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});
function C(a,c){a.V(c);c.d("click",u.bind(a,function(){this.Na()}))}u.va.prototype.e=function(){return u.c.prototype.e.call(this,"ul",{className:"vjs-menu"})};u.G=u.n.extend({f:function(a,c){u.n.call(this,a,c);c.selected?(this.r("vjs-selected"),this.a.setAttribute("aria-selected",f)):this.a.setAttribute("aria-selected",k)}});u.G.prototype.e=function(a,c){return u.n.prototype.e.call(this,"li",u.i.B({className:"vjs-menu-item",innerHTML:this.g.label},c))};u.G.prototype.q=function(){this.selected(f)};
u.G.prototype.selected=function(a){a?(this.r("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.z("vjs-selected"),this.a.setAttribute("aria-selected",k))};
u.ba=u.c.extend({f:function(a,c,d){this.O=a;c=u.i.B(ca(a),c);this.s={};this.jc=c.poster;this.Xb=c.controls;u.c.call(this,this,c,d);this.N("play",function(a){u.j(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Oc);this.d("play",this.yb);this.d("firstplay",this.Pc);this.d("pause",this.xb);this.d("progress",this.Rc);this.d("durationchange",this.Nc);this.d("error",this.ub);this.d("fullscreenchange",this.Qc);u.Ga[this.J]=
this;c.plugins&&u.i.la(c.plugins,function(a,c){this[a](c)},this)}});t=u.ba.prototype;t.g=u.options;t.C=function(){u.Ga[this.J]=h;this.O&&this.O.player&&(this.O.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.Ia);this.pa();this.h&&this.h.C();u.c.prototype.C.call(this)};
function ca(a){var c={sources:[],tracks:[]};u.i.B(c,u.lb(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,m=e.length;g<m;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?c.sources.push(u.lb(a)):"track"===d&&c.tracks.push(u.lb(a));return c}
t.e=function(){var a=this.a=u.c.prototype.e.call(this,"div"),c=this.O;c.removeAttribute("controls");c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes())for(var d=c.childNodes.length,e=0,g=c.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&c.removeChild(g[0]);c.id=c.id||"vjs_video_"+u.u++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.r("vjs-paused");this.width(this.g.width,
f);this.height(this.g.height,f);c.parentNode&&c.parentNode.insertBefore(a,c);u.nb(c,a);return a};
function D(a,c,d){a.h?E(a):"Html5"!==c&&a.O&&(a.a.removeChild(a.O),a.O=h);a.Z=c;a.X=k;var e=u.i.B({source:d,parentEl:a.a},a.g[c.toLowerCase()]);d&&(d.src==a.s.src&&0<a.s.currentTime&&(e.startTime=a.s.currentTime),a.s.src=d.src);a.h=new window.videojs[c](a,e);a.h.K(function(){this.b.Ma();if(!this.m.Ab){var a=this.b;a.sb=f;a.Ia=setInterval(u.bind(a,function(){this.s.bb<this.buffered().end(0)?this.j("progress"):1==F(this)&&(clearInterval(this.Ia),this.j("progress"))}),500);a.h.N("progress",function(){this.m.Ab=
f;var a=this.b;a.sb=k;clearInterval(a.Ia)})}this.m.Db||(a=this.b,a.tb=f,a.d("play",a.oc),a.d("pause",a.pa),a.h.N("timeupdate",function(){this.m.Db=f;G(this.b)}))})}function E(a){a.X=k;a.h.C();a.sb&&(a.sb=k,clearInterval(a.Ia));a.tb&&G(a);a.h=k}function G(a){a.tb=k;a.pa();a.t("play",a.oc);a.t("pause",a.pa)}t.oc=function(){this.Zb&&this.pa();this.Zb=setInterval(u.bind(this,function(){this.j("timeupdate")}),250)};t.pa=function(){clearInterval(this.Zb)};
t.Oc=function(){this.g.loop&&(this.currentTime(0),this.play())};t.yb=function(){u.z(this.a,"vjs-paused");u.r(this.a,"vjs-playing")};t.Pc=function(){this.g.starttime&&this.currentTime(this.g.starttime)};t.xb=function(){u.z(this.a,"vjs-playing");u.r(this.a,"vjs-paused")};t.Rc=function(){1==F(this)&&this.j("loadedalldata")};t.Nc=function(){this.duration(H(this,"duration"))};t.ub=function(a){u.log("Video Error",a)};t.Qc=function(){this.M?this.r("vjs-fullscreen"):this.z("vjs-fullscreen")};
function I(a,c,d){if(a.h&&a.h.X)a.h.K(function(){this[c](d)});else try{a.h[c](d)}catch(e){u.log(e)}}function H(a,c){if(a.h.X)try{return a.h[c]()}catch(d){if(a.h[c]===b)u.log("Video.js: "+c+" method not defined for "+a.Z+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+c+" unavailable on "+a.Z+" playback technology element.",d),a.h.X=k,d;u.log(d)}}}t.play=function(){I(this,"play");return this};t.pause=function(){I(this,"pause");return this};
t.paused=function(){return H(this,"paused")===k?k:f};t.currentTime=function(a){return a!==b?(this.s.qd=a,I(this,"setCurrentTime",a),this.tb&&this.j("timeupdate"),this):this.s.currentTime=H(this,"currentTime")||0};t.duration=function(a){return a!==b?(this.s.duration=parseFloat(a),this):this.s.duration};t.buffered=function(){var a=H(this,"buffered"),c=this.s.bb=this.s.bb||0;a&&(0<a.length&&a.end(0)!==c)&&(c=a.end(0),this.s.bb=c);return u.hb(0,c)};
function F(a){return a.duration()?a.buffered().end(0)/a.duration():0}t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.s.volume=a,I(this,"setVolume",a),u.Zc(a),this;a=parseFloat(H(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(I(this,"setMuted",a),this):H(this,"muted")||k};t.La=function(){return H(this,"supportsFullScreen")||k};
t.Ka=function(){var a=u.Cb.Ka;this.M=f;a?(u.d(document,a.da,u.bind(this,function(){this.M=document[a.M];this.M===k&&u.t(document,a.da,arguments.callee);this.j("fullscreenchange")})),this.h.m.kb===k&&this.g.flash.iFrameMode!==f&&(this.pause(),E(this),u.d(document,a.da,u.bind(this,function(){u.t(document,a.da,arguments.callee);D(this,this.Z,{src:this.s.src})}))),this.a[a.Vc]()):this.h.La()?(this.j("fullscreenchange"),I(this,"enterFullScreen")):(this.j("fullscreenchange"),this.Jc=f,this.Ec=document.documentElement.style.overflow,
u.d(document,"keydown",u.bind(this,this.bc)),document.documentElement.style.overflow="hidden",u.r(document.body,"vjs-full-window"),u.r(this.a,"vjs-fullscreen"),this.j("enterFullWindow"));return this};function J(a){var c=u.Cb.Ka;a.M=k;c?(a.h.m.kb===k&&a.g.flash.iFrameMode!==f&&(a.pause(),E(a),u.d(document,c.da,u.bind(a,function(){u.t(document,c.da,arguments.callee);D(this,this.Z,{src:this.s.src})}))),document[c.Bc]()):(a.h.La()?I(a,"exitFullScreen"):K(a),a.j("fullscreenchange"))}
t.bc=function(a){27===a.keyCode&&(this.M===f?J(this):K(this))};function K(a){a.Jc=k;u.t(document,"keydown",a.bc);document.documentElement.style.overflow=a.Ec;u.z(document.body,"vjs-full-window");u.z(a.a,"vjs-fullscreen");a.j("exitFullWindow")}
t.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.g.techOrder;d<e.length;d++){var g=u.W(e[d]),m=window.videojs[g];if(m.isSupported())for(var j=0,q=c;j<q.length;j++){var n=q[j];if(m.canPlaySource(n)){c={source:n,h:g};break a}}}c=k}c?(a=c.source,c=c.h,c==this.Z?this.src(a):D(this,c,a)):this.a.appendChild(u.e("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.Z].canPlaySource(a)?this.src(a.src):this.src([a]):(this.s.src=a,this.X?(I(this,"src",a),"auto"==this.g.preload&&this.load(),this.g.autoplay&&this.play()):this.K(function(){this.src(a)}));return this};t.load=function(){I(this,"load");return this};t.currentSrc=function(){return H(this,"currentSrc")||this.s.src||""};t.Ha=function(a){return a!==b?(I(this,"setPreload",a),this.g.preload=a,this):H(this,"preload")};
t.autoplay=function(a){return a!==b?(I(this,"setAutoplay",a),this.g.autoplay=a,this):H(this,"autoplay")};t.loop=function(a){return a!==b?(I(this,"setLoop",a),this.g.loop=a,this):H(this,"loop")};t.poster=function(a){a!==b&&(this.jc=a);return this.jc};t.controls=function(a){a!==b&&(this.Xb=a);return this.Xb};t.error=function(){return H(this,"error")};var L,M,N,O;
if(document.md!==b)L="requestFullscreen",M="exitFullscreen",N="fullscreenchange",O="fullScreen";else for(var P=["moz","webkit"],Q=P.length-1;0<=Q;Q--){var R=P[Q];if(("moz"!=R||document.mozFullScreenEnabled)&&document[R+"CancelFullScreen"]!==b)L=R+"RequestFullScreen",M=R+"CancelFullScreen",N=R+"fullscreenchange",O="webkit"==R?R+"IsFullScreen":R+"FullScreen"}L&&(u.Cb.Ka={Vc:L,Bc:M,da:N,M:O});
u.aa=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.N("play",u.bind(this,function(){var a,c=u.bind(this,this.na),g=u.bind(this,this.za);this.na();"ontouchstart"in window||(this.b.d("mouseover",c),this.b.d("mouseout",g),this.b.d("pause",u.bind(this,this.hc)),this.b.d("play",u.bind(this,this.Na)));a=k;this.b.d("touchstart",function(){a=f});this.b.d("touchmove",function(){a=k});this.b.d("touchend",u.bind(this,function(c){var e;a&&(e=this.o().className.search("fade-in"),-1!==e?this.za():this.na());
a=k;this.b.paused()||c.preventDefault()}))}))}});u.aa.prototype.g={rd:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.aa.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.aa.prototype.na=function(){u.c.prototype.na.call(this);this.b.j("controlsvisible")};u.aa.prototype.za=function(){u.c.prototype.za.call(this);this.b.j("controlshidden")};
u.Lb=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("play",u.bind(this,this.yb));a.d("pause",u.bind(this,this.xb))}});t=u.Lb.prototype;t.ja="Play";t.L=function(){return"vjs-play-control "+u.n.prototype.L.call(this)};t.q=function(){this.b.paused()?this.b.play():this.b.pause()};t.yb=function(){u.z(this.a,"vjs-paused");u.r(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};
t.xb=function(){u.z(this.a,"vjs-playing");u.r(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};u.ua=u.n.extend({f:function(a,c){u.n.call(this,a,c)}});u.ua.prototype.ja="Fullscreen";u.ua.prototype.L=function(){return"vjs-fullscreen-control "+u.n.prototype.L.call(this)};u.ua.prototype.q=function(){this.b.M?(J(this.b),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.b.Ka(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};
u.Ra=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.sa))}});u.Ra.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Ra.prototype.sa=function(){var a=this.b.Bb?this.b.s.currentTime:this.b.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.Aa(a,this.b.duration())};u.Sa=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.sa))}});
u.Sa.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};u.Sa.prototype.sa=function(){this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.Aa(this.b.duration()))};
u.Qb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Qb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.Ya=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.sa))}});
u.Ya.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Ya.prototype.sa=function(){this.b.duration()&&this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.Aa(this.b.duration()-this.b.currentTime()))};u.Xa=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Xa.prototype.g={children:{seekBar:{}}};u.Xa.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};
u.Mb=u.H.extend({f:function(a,c){u.H.call(this,a,c);a.d("timeupdate",u.bind(this,this.ra));a.K(u.bind(this,this.ra))}});t=u.Mb.prototype;t.g={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.ic="timeupdate";t.e=function(){return u.H.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
t.ra=function(){var a=this.b.Bb?this.b.s.currentTime:this.b.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.mb(),2));this.a.setAttribute("aria-valuetext",u.Aa(a,this.b.duration()))};t.mb=function(){return this.b.currentTime()/this.b.duration()};t.Fa=function(a){u.H.prototype.Fa.call(this,a);this.b.Bb=f;this.fd=!this.b.paused();this.b.pause()};t.vb=function(a){a=B(this,a)*this.b.duration();a==this.b.duration()&&(a-=0.1);this.b.currentTime(a)};
t.wb=function(a){u.H.prototype.wb.call(this,a);this.b.Bb=k;this.fd&&this.b.play()};t.nc=function(){this.b.currentTime(this.b.currentTime()+5)};t.mc=function(){this.b.currentTime(this.b.currentTime()-5)};u.Ua=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("progress",u.bind(this,this.update))}});u.Ua.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
u.Ua.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*F(this.b),2)+"%")};u.Kb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Kb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.Nb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Nb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};
u.$a=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.h&&(a.h.m&&a.h.m.ga===k)&&this.r("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.m&&a.h.m.ga===k?this.r("vjs-hidden"):this.z("vjs-hidden")}))}});u.$a.prototype.g={children:{volumeBar:{}}};u.$a.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};
u.Rb=u.H.extend({f:function(a,c){u.H.call(this,a,c);a.d("volumechange",u.bind(this,this.ra));a.K(u.bind(this,this.ra));setTimeout(u.bind(this,this.update),0)}});t=u.Rb.prototype;t.ra=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.b.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.b.volume(),2)+"%")};t.g={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.ic="volumechange";
t.e=function(){return u.H.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.vb=function(a){this.b.volume(B(this,a))};t.mb=function(){return this.b.volume()};t.nc=function(){this.b.volume(this.b.volume()+0.1)};t.mc=function(){this.b.volume(this.b.volume()-0.1)};u.Tb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Tb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};
u.Sb=u.c.extend({f:function(a,c){u.c.call(this,a,c)}});u.Sb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};u.wa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.h&&(a.h.m&&a.h.m.ga===k)&&this.r("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.m&&a.h.m.ga===k?this.r("vjs-hidden"):this.z("vjs-hidden")}))}});
u.wa.prototype.e=function(){return u.n.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.wa.prototype.q=function(){this.b.muted(this.b.muted()?k:f)};
u.wa.prototype.update=function(){var a=this.b.volume(),c=3;0===a||this.b.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.b.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.z(this.a,"vjs-vol-"+a);u.r(this.a,"vjs-vol-"+c)};u.Wa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.poster()||this.A();a.d("play",u.bind(this,this.A))}});
u.Wa.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1}),c=this.b.poster();c&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+c+'")':a.appendChild(u.e("img",{src:c})));return a};u.Wa.prototype.q=function(){this.b.play()};
u.Jb=u.c.extend({f:function(a,c){u.c.call(this,a,c);a.d("canplay",u.bind(this,this.A));a.d("canplaythrough",u.bind(this,this.A));a.d("playing",u.bind(this,this.A));a.d("seeked",u.bind(this,this.A));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.A));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}});
u.Jb.prototype.e=function(){var a,c;"string"==typeof this.b.o().style.WebkitBorderRadius||"string"==typeof this.b.o().style.MozBorderRadius||"string"==typeof this.b.o().style.kd||"string"==typeof this.b.o().style.ld?(a="vjs-loading-spinner",c='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",c="");return u.c.prototype.e.call(this,
"div",{className:a,innerHTML:c})};u.Pa=u.n.extend({f:function(a,c){u.n.call(this,a,c);a.d("play",u.bind(this,this.A))}});u.Pa.prototype.e=function(){return u.n.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};u.Pa.prototype.q=function(){this.b.play()};u.p=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d)}});u.p.prototype.q=function(){this.b.controls()&&(this.b.paused()?this.b.play():this.b.pause())};
u.p.prototype.m={ga:f,kb:k,Ab:k,Db:k};u.media={};u.media.Oa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function da(){var a=u.media.Oa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Oa.length-1;0<=i;i--)u.p.prototype[u.media.Oa[i]]=da();
u.l=u.p.extend({f:function(a,c,d){u.p.call(this,a,c,d);this.m.ga=u.l.Ac();this.m.Lc=!u.sc;(c=c.source)&&this.a.currentSrc==c.src?a.j("loadstart"):c&&(this.a.src=c.src);a.K(function(){this.g.autoplay&&this.paused()&&(this.O.poster=h,this.play())});this.d("click",this.q);for(a=u.l.Ta.length-1;0<=a;a--)u.d(this.a,u.l.Ta[a],u.bind(this.b,this.Gc));this.Ma()}});t=u.l.prototype;t.C=function(){u.p.prototype.C.call(this)};
t.e=function(){var a=this.b,c=a.O;if(!c||this.m.Lc===k)c?(a.o().removeChild(c),c=c.cloneNode(k)):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.nb(c,a.o());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.g[g]!==h&&(c[g]=a.g[g])}return c};t.Gc=function(a){this.j(a);a.stopPropagation()};t.play=function(){this.a.play()};t.pause=function(){this.a.pause()};t.paused=function(){return this.a.paused};t.currentTime=function(){return this.a.currentTime};
t.Yc=function(a){try{this.a.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.a.duration||0};t.buffered=function(){return this.a.buffered};t.volume=function(){return this.a.volume};t.cd=function(a){this.a.volume=a};t.muted=function(){return this.a.muted};t.ad=function(a){this.a.muted=a};t.width=function(){return this.a.offsetWidth};t.height=function(){return this.a.offsetHeight};
t.La=function(){return"function"==typeof this.a.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:k};t.src=function(a){this.a.src=a};t.load=function(){this.a.load()};t.currentSrc=function(){return this.a.currentSrc};t.Ha=function(){return this.a.Ha};t.bd=function(a){this.a.Ha=a};t.autoplay=function(){return this.a.autoplay};t.Xc=function(a){this.a.autoplay=a};t.loop=function(){return this.a.loop};t.$c=function(a){this.a.loop=a};t.error=function(){return this.a.error};
u.l.isSupported=function(){return!!document.createElement("video").canPlayType};u.l.cb=function(a){return!!document.createElement("video").canPlayType(a.type)};u.l.Ac=function(){var a=u.Za.volume;u.Za.volume=a/2+0.1;return a!==u.Za.volume};u.l.Ta="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.qc&&3>u.pc&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
u.k=u.p.extend({f:function(a,c,d){u.p.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.a=u.e("div",{id:a.id()+"_temp_flash"}),m=a.id()+"_flash_api";a=a.g;var j=u.i.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Ha,loop:a.loop,muted:a.muted},c.flashVars),q=u.i.B({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.i.B({id:m,name:m,"class":"vjs-tech"},c.attributes);d&&(j.src=encodeURIComponent(u.cc(d.src)));
u.nb(g,e);c.startTime&&this.K(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!u.rc){var s=u.e("iframe",{id:m+"_iframe",name:m+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});j.readyFunction="ready";j.eventProxyFunction="events";j.errorEventProxyFunction="errors";u.d(s,"load",u.bind(this,function(){var a,d=s.contentWindow;a=s.contentDocument?s.contentDocument:s.contentWindow.document;a.write(u.k.dc(c.swf,j,q,n));d.player=
this.b;d.ready=u.bind(this.b,function(c){c=a.getElementById(c);var d=this.h;d.a=c;u.d(c,"click",d.bind(d.q));u.k.eb(d)});d.events=u.bind(this.b,function(a,c){this&&"flash"===this.Z&&this.j(c)});d.errors=u.bind(this.b,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(s,g)}else u.k.Fc(c.swf,g,j,q,n)}});t=u.k.prototype;t.C=function(){u.p.prototype.C.call(this)};t.play=function(){this.a.vjs_play()};t.pause=function(){this.a.vjs_pause()};
t.src=function(a){a=u.cc(a);this.a.vjs_src(a);if(this.b.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.load=function(){this.a.vjs_load()};t.poster=function(){this.a.vjs_getProperty("poster")};t.buffered=function(){return u.hb(0,this.a.vjs_getProperty("buffered"))};t.La=r(k);var S=u.k.prototype,T="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),U="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function ea(){var a=T[V],c=a.charAt(0).toUpperCase()+a.slice(1);S["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}function W(a){S[a]=function(){return this.a.vjs_getProperty(a)}}var V;for(V=0;V<T.length;V++)W(T[V]),ea();for(V=0;V<U.length;V++)W(U[V]);u.k.isSupported=function(){return 10<=u.k.version()[0]};u.k.cb=function(a){if(a.type in u.k.Ic)return"maybe"};u.k.Ic={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
u.k.onReady=function(a){a=u.o(a);var c=a.player||a.parentNode.player,d=c.h;a.player=c;d.a=a;d.d("click",d.q);u.k.eb(d)};u.k.eb=function(a){a.o().vjs_getProperty?a.Ma():setTimeout(function(){u.k.eb(a)},50)};u.k.onEvent=function(a,c){u.o(a).player.j(c)};u.k.onError=function(a,c){u.o(a).player.j("error");u.log("Flash Error",c,a)};
u.k.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.k.Fc=function(a,c,d,e,g){a=u.k.dc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var m=d.childNodes[0];setTimeout(function(){m.style.display="block"},1E3)};
u.k.dc=function(a,c,d,e){var g="",m="",j="";c&&u.i.la(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.i.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.i.la(d,function(a,c){m+='<param name="'+a+'" value="'+c+'" />'});e=u.i.B({data:a,width:"100%",height:"100%"},e);u.i.la(e,function(a,c){j+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+j+">"+m+"</object>"};
u.wc=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d);if(!a.g.sources||0===a.g.sources.length){c=0;for(d=a.g.techOrder;c<d.length;c++){var e=u.W(d[c]),g=window.videojs[e];if(g&&g.isSupported()){D(a,e);break}}}else a.src(a.g.sources)}});function X(a){a.qa=a.qa||[];return a.qa}function fa(a,c,d){for(var e=a.qa,g=0,m=e.length,j,q;g<m;g++)j=e[g],j.id()===c?(j.show(),q=j):d&&(j.F()==d&&0<j.mode())&&j.disable();(c=q?q.F():d?d:k)&&a.j(c+"trackchange")}
u.R=u.c.extend({f:function(a,c){u.c.call(this,a,c);this.J=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.u++;this.lc=c.src;this.Cc=c["default"]||c.dflt;this.sd=c.title;this.pd=c.srclang;this.Kc=c.label;this.ca=[];this.Ub=[];this.ea=this.fa=0;this.b.d("fullscreenchange",u.bind(this,this.xc))}});t=u.R.prototype;t.F=p("w");t.src=p("lc");t.ib=p("Cc");t.label=p("Kc");t.readyState=p("fa");t.mode=p("ea");t.xc=function(){this.a.style.fontSize=this.b.M?140*(screen.width/this.b.width())+"%":""};
t.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-"+this.w+" vjs-text-track"})};t.show=function(){ga(this);this.ea=2;u.c.prototype.show.call(this)};t.A=function(){ga(this);this.ea=1;u.c.prototype.A.call(this)};t.disable=function(){2==this.ea&&this.A();this.b.t("timeupdate",u.bind(this,this.update,this.J));this.b.t("ended",u.bind(this,this.reset,this.J));this.reset();this.b.P.textTrackDisplay.removeChild(this);this.ea=0};
function ga(a){0===a.fa&&a.load();0===a.ea&&(a.b.d("timeupdate",u.bind(a,a.update,a.J)),a.b.d("ended",u.bind(a,a.reset,a.J)),("captions"===a.w||"subtitles"===a.w)&&a.b.P.textTrackDisplay.V(a))}t.load=function(){0===this.fa&&(this.fa=1,u.get(this.lc,u.bind(this,this.Sc),u.bind(this,this.ub)))};t.ub=function(a){this.error=a;this.fa=3;this.j("error")};
t.Sc=function(a){var c,d;a=a.split("\n");for(var e="",g=1,m=a.length;g<m;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.ca.length;c={id:c,index:this.ca.length};d=e.split(" --\x3e ");c.startTime=ha(d[0]);c.ma=ha(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.ca.push(c)}this.fa=2;this.j("loaded")};
function ha(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.ca.length){var a=this.b.currentTime();if(this.zb===b||a<this.zb||this.Ca<=a){var c=this.ca,d=this.b.duration(),e=0,g=k,m=[],j,q,n,s;a>=this.Ca||this.Ca===b?s=this.jb!==b?this.jb:0:(g=f,s=this.rb!==b?this.rb:c.length-1);for(;;){n=c[s];if(n.ma<=a)e=Math.max(e,n.ma),n.ya&&(n.ya=k);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.ya&&(n.ya=k),!g)break}else g?(m.splice(0,0,n),q===b&&(q=s),j=s):(m.push(n),j===b&&(j=s),q=s),d=Math.min(d,n.ma),e=Math.max(e,n.startTime),
n.ya=f;if(g)if(0===s)break;else s--;else if(s===c.length-1)break;else s++}this.Ub=m;this.Ca=d;this.zb=e;this.jb=j;this.rb=q;a=this.Ub;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=c;this.j("cuechange")}}};t.reset=function(){this.Ca=0;this.zb=this.b.duration();this.rb=this.jb=0};u.Gb=u.R.extend();u.Gb.prototype.w="captions";u.Ob=u.R.extend();u.Ob.prototype.w="subtitles";u.Ib=u.R.extend();u.Ib.prototype.w="chapters";
u.Pb=u.c.extend({f:function(a,c,d){u.c.call(this,a,c,d);if(a.g.tracks&&0<a.g.tracks.length){c=this.b;a=a.g.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=c,m=e.kind,j=e.label,q=e.language,n=e;e=g.qa=g.qa||[];n=n||{};n.kind=m;n.label=j;n.language=q;m=u.W(m||"subtitles");g=new window.videojs[m+"Track"](g,n);e.push(g)}}}});u.Pb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};
u.T=u.G.extend({f:function(a,c){var d=this.$=c.track;c.label=d.label();c.selected=d.ib();u.G.call(this,a,c);this.b.d(d.F()+"trackchange",u.bind(this,this.update))}});u.T.prototype.q=function(){u.G.prototype.q.call(this);fa(this.b,this.$.J,this.$.F())};u.T.prototype.update=function(){2==this.$.mode()?this.selected(f):this.selected(k)};u.Va=u.T.extend({f:function(a,c){c.track={F:function(){return c.kind},Tc:a,label:r("Off"),ib:r(k),mode:r(k)};u.T.call(this,a,c);this.selected(f)}});
u.Va.prototype.q=function(){u.T.prototype.q(this);fa(this.b,this.$.J,this.$.F())};u.Va.prototype.update=function(){for(var a=X(this.b),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.F()==this.$.F()&&2==e.mode()&&(g=k);g?this.selected(f):this.selected(k)};u.S=u.n.extend({f:function(a,c){u.n.call(this,a,c);this.Ba=this.gb();0===this.oa.length&&this.A();this.d("keyup",this.Y);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});t=u.S.prototype;t.ia=k;
t.gb=function(){var a=new u.va(this.b);a.o().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.W(this.w),dd:-1}));C(a,new u.Va(this.b,{kind:this.w}));this.oa=this.Yb();for(var c=0;c<this.oa.length;c++)C(a,this.oa[c]);this.V(a);return a};t.Yb=function(){for(var a=[],c,d=0;d<X(this.b).length;d++)c=X(this.b)[d],c.F()===this.w&&a.push(new u.T(this.b,{track:c}));return a};t.L=function(){return this.className+" vjs-menu-button "+u.n.prototype.L.call(this)};t.Ea=l();t.Da=l();
t.q=function(){this.N("mouseout",u.bind(this,function(){this.Ba.Na();this.a.blur()}));this.ia?Y(this):ia(this)};t.Y=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.ia?Y(this):ia(this);27==a.which&&(a.preventDefault(),this.ia&&Y(this))};function ia(a){a.ia=f;a.Ba.hc();a.a.setAttribute("aria-pressed",f);a.a.children[1].children[0].focus()}function Y(a){a.ia=k;a.Ba.Na();a.a.setAttribute("aria-pressed",k)}
u.ta=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Captions Menu")}});u.ta.prototype.w="captions";u.ta.prototype.ja="Captions";u.ta.prototype.className="vjs-captions-button";u.xa=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Subtitles Menu")}});u.xa.prototype.w="subtitles";u.xa.prototype.ja="Subtitles";u.xa.prototype.className="vjs-subtitles-button";
u.Hb=u.S.extend({f:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Chapters Menu")}});t=u.Hb.prototype;t.w="chapters";t.ja="Chapters";t.className="vjs-chapters-button";t.Yb=function(){for(var a=[],c,d=0;d<X(this.b).length;d++)c=X(this.b)[d],c.F()===this.w&&a.push(new u.T(this.b,{track:c}));return a};
t.gb=function(){for(var a=X(this.b),c=0,d=a.length,e,g,m=this.oa=[];c<d;c++)if(e=a[c],e.F()==this.w&&e.ib()){if(2>e.readyState()){this.nd=e;e.d("loaded",u.bind(this,this.gb));return}g=e;break}a=this.Ba=new u.va(this.b);a.a.appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.W(this.w),dd:-1}));if(g){e=g.ca;for(var j,c=0,d=e.length;c<d;c++)j=e[c],j=new u.Qa(this.b,{track:g,cue:j}),m.push(j),a.V(j)}this.V(a);0<this.oa.length&&this.show();return a};
u.Qa=u.G.extend({f:function(a,c){var d=this.$=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ma;u.G.call(this,a,c);d.d("cuechange",u.bind(this,this.update))}});u.Qa.prototype.q=function(){u.G.prototype.q.call(this);this.b.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.Qa.prototype.update=function(){var a=this.cue,c=this.b.currentTime();a.startTime<=c&&c<a.ma?this.selected(f):this.selected(k)};
u.i.B(u.aa.prototype.g.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var j,q,n=a[e];if(n&&"object"===typeof n)for(j in n)Object.prototype.hasOwnProperty.call(n,j)&&(q=d(n,j),q!==b?n[j]=q:delete n[j]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.ab=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),v(c,a)));else{u.Vb();break}else u.gd||u.Vb()};u.Vb=function(){setTimeout(u.ab,1)};u.N(window,"load",function(){u.gd=f});u.ab();u.Uc=function(a,c){u.ba.prototype[a]=c};var ja=this;ja.hd=f;function $(a,c){var d=a.split("."),e=ja;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.cache",u.ka);$("videojs.Component",u.c);u.c.prototype.dispose=u.c.prototype.C;u.c.prototype.createEl=u.c.prototype.e;u.c.prototype.el=u.c.prototype.o;u.c.prototype.addChild=u.c.prototype.V;u.c.prototype.children=u.c.prototype.children;u.c.prototype.on=u.c.prototype.d;u.c.prototype.off=u.c.prototype.t;u.c.prototype.one=u.c.prototype.N;u.c.prototype.trigger=u.c.prototype.j;u.c.prototype.triggerReady=u.c.prototype.Ma;
u.c.prototype.show=u.c.prototype.show;u.c.prototype.hide=u.c.prototype.A;u.c.prototype.width=u.c.prototype.width;u.c.prototype.height=u.c.prototype.height;u.c.prototype.dimensions=u.c.prototype.Dc;u.c.prototype.ready=u.c.prototype.K;$("videojs.Player",u.ba);u.ba.prototype.dispose=u.ba.prototype.C;$("videojs.MediaLoader",u.wc);$("videojs.TextTrackDisplay",u.Pb);$("videojs.ControlBar",u.aa);$("videojs.Button",u.n);$("videojs.PlayToggle",u.Lb);$("videojs.FullscreenToggle",u.ua);
$("videojs.BigPlayButton",u.Pa);$("videojs.LoadingSpinner",u.Jb);$("videojs.CurrentTimeDisplay",u.Ra);$("videojs.DurationDisplay",u.Sa);$("videojs.TimeDivider",u.Qb);$("videojs.RemainingTimeDisplay",u.Ya);$("videojs.Slider",u.H);$("videojs.ProgressControl",u.Xa);$("videojs.SeekBar",u.Mb);$("videojs.LoadProgressBar",u.Ua);$("videojs.PlayProgressBar",u.Kb);$("videojs.SeekHandle",u.Nb);$("videojs.VolumeControl",u.$a);$("videojs.VolumeBar",u.Rb);$("videojs.VolumeLevel",u.Tb);
$("videojs.VolumeHandle",u.Sb);$("videojs.MuteToggle",u.wa);$("videojs.PosterImage",u.Wa);$("videojs.Menu",u.va);$("videojs.MenuItem",u.G);$("videojs.SubtitlesButton",u.xa);$("videojs.CaptionsButton",u.ta);$("videojs.ChaptersButton",u.Hb);$("videojs.MediaTechController",u.p);u.p.prototype.features=u.p.prototype.m;u.p.prototype.m.volumeControl=u.p.prototype.m.ga;u.p.prototype.m.fullscreenResize=u.p.prototype.m.kb;u.p.prototype.m.progressEvents=u.p.prototype.m.Ab;u.p.prototype.m.timeupdateEvents=u.p.prototype.m.Db;
$("videojs.Html5",u.l);u.l.Events=u.l.Ta;u.l.isSupported=u.l.isSupported;u.l.canPlaySource=u.l.cb;u.l.prototype.setCurrentTime=u.l.prototype.Yc;u.l.prototype.setVolume=u.l.prototype.cd;u.l.prototype.setMuted=u.l.prototype.ad;u.l.prototype.setPreload=u.l.prototype.bd;u.l.prototype.setAutoplay=u.l.prototype.Xc;u.l.prototype.setLoop=u.l.prototype.$c;$("videojs.Flash",u.k);u.k.isSupported=u.k.isSupported;u.k.canPlaySource=u.k.cb;u.k.onReady=u.k.onReady;$("videojs.TextTrack",u.R);u.R.prototype.label=u.R.prototype.label;
$("videojs.CaptionsTrack",u.Gb);$("videojs.SubtitlesTrack",u.Ob);$("videojs.ChaptersTrack",u.Ib);$("videojs.autoSetup",u.ab);$("videojs.plugin",u.Uc);$("videojs.createTimeRange",u.hb);
